import Link from "next/link";
import { notFound } from "next/navigation";
import { ClipboardCheck, Plus, ArrowRight } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { copy, isLocale, type Locale } from "@/lib/i18n";
const statuses={scheduled:"Scheduled",in_progress:"In progress",completed:"Completed",report_ready:"Report ready",closed:"Closed"} as const;
export default async function InspectionsPage({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params; if(!isLocale(locale)) notFound();
 const t=copy[locale as Locale]; const ui=locale==="fr"?{title:"Inspections",desc:"Inspectez les actifs, consignez les constats et produisez des rapports fondés sur des preuves.",new:"Nouvelle inspection",scheduled:"Planifiées",progress:"En cours",ready:"Rapport prêt",queue:"File des inspections",empty:"Aucune inspection pour le moment",emptyDesc:"Créez la première inspection d’un actif KRAM.",create:"Créer une inspection",unassigned:"Inspecteur non assigné"}:locale==="pt"?{title:"Inspeções",desc:"Inspecione ativos, registe constatações e produza relatórios baseados em evidências.",new:"Nova inspeção",scheduled:"Agendadas",progress:"Em curso",ready:"Relatório pronto",queue:"Fila de inspeções",empty:"Ainda não há inspeções",emptyDesc:"Crie a primeira inspeção de um ativo KRAM.",create:"Criar inspeção",unassigned:"Inspetor não atribuído"}:{title:"Inspections",desc:"Inspect assets, record findings and produce evidence-backed reports.",new:"New inspection",scheduled:"Scheduled",progress:"In progress",ready:"Report ready",queue:"Inspection queue",empty:"No inspections yet",emptyDesc:"Create the first inspection for a KRAM asset.",create:"Create inspection",unassigned:"Inspector not assigned"}; const supabase=await createClient();
 const {data:rows}=await supabase.from("inspections").select("id,inspection_type,status,scheduled_for,inspector_name,created_at,assets(id,name,reference_code)").order("created_at",{ascending:false});
 const all=rows??[]; const scheduled=all.filter(x=>x.status==="scheduled").length; const active=all.filter(x=>x.status==="in_progress").length; const ready=all.filter(x=>x.status==="report_ready").length;
 return <div className="space-y-7">
 <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--kram-orange)]">{t.nav.inspections}</p><div className="mt-2 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--kram-charcoal)] text-white"><ClipboardCheck size={19}/></div><h1 className="text-3xl font-bold tracking-[-0.045em] text-zinc-950">{ui.title}</h1></div><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">{ui.desc}</p></div><Link href={"/"+locale+"/ops/inspections/new"} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--kram-orange)] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/> {ui.new}</Link></section>
 <section className="grid gap-4 sm:grid-cols-3">{[["Scheduled",scheduled],["In progress",active],["Report ready",ready]].map(([label,value])=><div key={label as string} className="rounded-2xl border border-[var(--kram-border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-400">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight text-zinc-950">{value}</p></div>)}</section>
 <section className="overflow-hidden rounded-2xl border border-[var(--kram-border)] bg-white"><div className="border-b border-zinc-100 px-5 py-4"><h2 className="text-base font-bold text-zinc-950">{ui.queue}</h2></div>{all.length?<div className="divide-y divide-zinc-100">{all.map(i=>{const a=Array.isArray(i.assets)?i.assets[0]:i.assets;return <Link key={i.id} href={"/"+locale+"/ops/inspections/"+i.id} className="group flex items-center justify-between gap-5 px-5 py-4 hover:bg-zinc-50/70"><div><p className="text-sm font-bold capitalize text-zinc-900 group-hover:text-[var(--kram-orange)]">{i.inspection_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-zinc-400">{a?.name??"—"} · {a?.reference_code??"—"} · {i.inspector_name||ui.unassigned}</p></div><div className="flex items-center gap-3"><span className="hidden rounded-full border border-zinc-200 px-2.5 py-1 text-[11px] font-semibold text-zinc-600 sm:inline-flex">{statuses[i.status as keyof typeof statuses]}</span><ArrowRight size={16} className="text-zinc-300 group-hover:text-[var(--kram-orange)]"/></div></Link>})}</div>:<div className="flex min-h-72 flex-col items-center justify-center px-6 text-center"><ClipboardCheck size={22} className="text-zinc-300"/><h3 className="mt-4 text-sm font-bold text-zinc-800">{ui.empty}</h3><p className="mt-1 text-sm text-zinc-500">{ui.emptyDesc}</p><Link href={"/"+locale+"/ops/inspections/new"} className="mt-4 text-xs font-bold text-[var(--kram-orange)]">{ui.create}</Link></div>}</section>
 </div>;
}