"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const schema=z.object({branchId:z.string().uuid(),fullName:z.string().trim().min(2).max(160),email:z.string().trim().email().max(254).optional().or(z.literal("")),primaryPhone:z.string().trim().max(40).optional(),alternativePhone:z.string().trim().max(40).optional(),residencyCountry:z.string().trim().max(100).optional(),residencyCity:z.string().trim().max(100).optional(),residencyAddress:z.string().trim().max(240).optional(),preferredLanguage:z.enum(["fr","en","pt"]),preferredContactMethod:z.enum(["whatsapp","email","phone"]),trustedFullName:z.string().trim().max(160).optional(),trustedRelationship:z.string().trim().max(100).optional(),trustedPrimaryPhone:z.string().trim().max(40).optional(),trustedAlternativePhone:z.string().trim().max(40).optional(),trustedEmail:z.string().trim().email().max(254).optional().or(z.literal("")),trustedResidencyCountry:z.string().trim().max(100).optional(),trustedResidencyCity:z.string().trim().max(100).optional(),trustedResidencyAddress:z.string().trim().max(240).optional(),trustedPreferredLanguage:z.enum(["fr","en","pt"]),trustedPreferredContactMethod:z.enum(["whatsapp","email","phone"]),trustedSameAsClient:z.boolean(),trustedNotes:z.string().trim().max(1000).optional(),notes:z.string().trim().max(2000).optional()});
export type ClientActionState={success:boolean;message:string};
export async function createClientRecord(_prev:ClientActionState,formData:FormData):Promise<ClientActionState>{
 const parsed=schema.safeParse({fullName:formData.get("fullName"),branchId:formData.get("branchId"),email:formData.get("email"),primaryPhone:formData.get("primaryPhone"),alternativePhone:formData.get("alternativePhone"),residencyCountry:formData.get("residencyCountry"),residencyCity:formData.get("residencyCity"),residencyAddress:formData.get("residencyAddress"),preferredLanguage:formData.get("preferredLanguage")||"fr",preferredContactMethod:formData.get("preferredContactMethod")||"whatsapp",trustedFullName:formData.get("trustedFullName"),trustedRelationship:formData.get("trustedRelationship"),trustedPrimaryPhone:formData.get("trustedPrimaryPhone"),trustedAlternativePhone:formData.get("trustedAlternativePhone"),trustedEmail:formData.get("trustedEmail"),trustedResidencyCountry:formData.get("trustedResidencyCountry"),trustedResidencyCity:formData.get("trustedResidencyCity"),trustedResidencyAddress:formData.get("trustedResidencyAddress"),trustedPreferredLanguage:formData.get("trustedPreferredLanguage")||"fr",trustedPreferredContactMethod:formData.get("trustedPreferredContactMethod")||"whatsapp",trustedSameAsClient:formData.get("trustedSameAsClient")==="true",trustedNotes:formData.get("trustedNotes"),notes:formData.get("notes")});
 if(!parsed.success)return{success:false,message:"Please provide a valid client name and contact details."};
 const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); const userId=claims?.claims?.sub;
 if(!userId)return{success:false,message:"Your session is no longer valid."};
 const {data:membership}=await supabase.from("organization_members").select("organization_id,role,scope_level,country_id,branch_id").eq("user_id",userId).eq("status","active").limit(1).maybeSingle();
 if(!membership)return{success:false,message:"You are not authorized to create clients."};
 if(!["owner","admin","regional_admin"].includes(membership.role))return{success:false,message:"You are not authorized to create clients."};
 const {data:branch}=await supabase.from("branches").select("id,country_id").eq("id",parsed.data.branchId).eq("organization_id",membership.organization_id).maybeSingle();
 if(!branch)return{success:false,message:"The selected branch is not valid."};
 if(membership.scope_level==="country" && branch.country_id!==membership.country_id)return{success:false,message:"You cannot create a client outside your country scope."};
 if(membership.scope_level==="branch" && branch.id!==membership.branch_id)return{success:false,message:"You cannot create a client outside your branch scope."};
 const {error}=await supabase.from("clients").insert({organization_id:membership.organization_id,branch_id:parsed.data.branchId,full_name:parsed.data.fullName,email:parsed.data.email||null,primary_phone:parsed.data.primaryPhone||null,alternative_phone:parsed.data.alternativePhone||null,residency_country:parsed.data.residencyCountry||null,residency_city:parsed.data.residencyCity||null,residency_address:parsed.data.residencyAddress||null,preferred_language:parsed.data.preferredLanguage,preferred_contact_method:parsed.data.preferredContactMethod,notes:parsed.data.notes||null});
 if(error)return{success:false,message:"The client could not be created."};
 if(parsed.data.trustedFullName){const trusted={organization_id:membership.organization_id,client_id:(await supabase.from("clients").select("id").eq("organization_id",membership.organization_id).eq("full_name",parsed.data.fullName).order("created_at",{ascending:false}).limit(1).single()).data?.id,full_name:parsed.data.trustedFullName,relationship:parsed.data.trustedRelationship||null,primary_phone:parsed.data.trustedPrimaryPhone||null,alternative_phone:parsed.data.trustedAlternativePhone||null,email:parsed.data.trustedEmail||null,residency_country:parsed.data.trustedResidencyCountry||null,residency_city:parsed.data.trustedResidencyCity||null,residency_address:parsed.data.trustedResidencyAddress||null,preferred_language:parsed.data.trustedPreferredLanguage,preferred_contact_method:parsed.data.trustedPreferredContactMethod,same_as_client:parsed.data.trustedSameAsClient,notes:parsed.data.trustedNotes||null};
  if(!trusted.client_id)return{success:false,message:"The client was created, but the trusted contact could not be linked."};
  const {error:contactError}=await supabase.from("client_authorized_contacts").insert(trusted); if(contactError)return{success:false,message:"The client was created, but the trusted contact could not be saved."}; }
 revalidatePath("/fr/ops/clients");revalidatePath("/en/ops/clients");revalidatePath("/pt/ops/clients");
 return{success:true,message:"Client created successfully."};
}
