"use client";
import {useActionState,useEffect,useState} from "react";
import {Loader2,Save,UserRoundPlus} from "lucide-react";
import {createClientRecord} from "./actions";
import {createClient as createSupabaseClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/i18n";

const labels={fr:{name:"Nom complet",email:"E-mail",primary:"Numéro principal",alternative:"Numéro alternatif",country:"Pays de résidence",city:"Ville de résidence",address:"Adresse de résidence",language:"Langue préférée",method:"Mode de contact préféré",branch:"Agence / ville",select:"Sélectionner une agence",trusted:"Personne de confiance / représentant",same:"Même coordonnées que le client",relationship:"Lien avec le client",notes:"Notes",save:"Créer le client",saving:"Création..."},en:{name:"Full name",email:"Email",primary:"Primary number",alternative:"Alternative number",country:"Country of residence",city:"City of residence",address:"Residence address",language:"Preferred language",method:"Preferred contact method",branch:"Branch / city",select:"Select a branch",trusted:"Trusted person / authorised representative",same:"Same contact details as client",relationship:"Relationship to client",notes:"Notes",save:"Create client",saving:"Creating..."},pt:{name:"Nome completo",email:"E-mail",primary:"Número principal",alternative:"Número alternativo",country:"País de residência",city:"Cidade de residência",address:"Morada de residência",language:"Idioma preferido",method:"Meio de contacto preferido",branch:"Sucursal / cidade",select:"Selecionar uma sucursal",trusted:"Pessoa de confiança / representante autorizado",same:"Mesmos dados de contacto do cliente",relationship:"Relação com o cliente",notes:"Notas",save:"Criar cliente",saving:"A criar..."}} as const;
type Branch={id:string;name:string;city:string};
export function ClientCreateForm({locale}:{locale:Locale}){const t=labels[locale],[state,action,pending]=useActionState(createClientRecord,{success:false,message:""});const[branches,setBranches]=useState<Branch[]>([]);const[loading,setLoading]=useState(true);const[same,setSame]=useState(false);const[client,setClient]=useState({fullName:"",email:"",primaryPhone:"",alternativePhone:"",country:"",city:"",address:"",language:"fr",method:"whatsapp"});const[trusted,setTrusted]=useState({fullName:"",email:"",primaryPhone:"",alternativePhone:"",country:"",city:"",address:"",language:"fr",method:"whatsapp"});const setClientField=(k:string,v:string)=>setClient(x=>({...x,[k]:v}));const setTrustedField=(k:string,v:string)=>setTrusted(x=>({...x,[k]:v}));
useEffect(()=>{const s=createSupabaseClient();void(async()=>{const{data}=await s.from("branches").select("id,name,city").order("name");setBranches(data??[]);setLoading(false)})()},[]);
return <form action={action} className="space-y-6 rounded-2xl border border-[var(--kram-border)] bg-white p-6 shadow-sm">
<section><h2 className="text-sm font-black uppercase tracking-wider">Client details</h2><div className="mt-4 grid gap-4 md:grid-cols-2">
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.name}</span><input name="fullName" required value={client.fullName} onChange={e=>setClientField("fullName",e.target.value)} autoComplete="name" className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.email}</span><input name="email" type="email" value={client.email} onChange={e=>setClientField("email",e.target.value)} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.primary}</span><input name="primaryPhone" required value={client.primaryPhone} onChange={e=>setClientField("primaryPhone",e.target.value)} placeholder="+243812345678" inputMode="tel" autoComplete="tel" className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.alternative}</span><input name="alternativePhone" value={client.alternativePhone} onChange={e=>setClientField("alternativePhone",e.target.value)} placeholder="+243812345678" inputMode="tel" autoComplete="tel" className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.country}</span><input name="residencyCountry" value={client.country} onChange={e=>setClientField("country",e.target.value)} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.city}</span><input name="residencyCity" value={client.city} onChange={e=>setClientField("city",e.target.value)} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.address}</span><input name="residencyAddress" value={client.address} onChange={e=>setClientField("address",e.target.value)} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.language}</span><select name="preferredLanguage" value={client.language} onChange={e=>setClientField("language",e.target.value)} className="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm"><option value="fr">Français</option><option value="en">English</option><option value="pt">Português</option></select></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.method}</span><select name="preferredContactMethod" value={client.method} onChange={e=>setClientField("method",e.target.value)} className="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm"><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="phone">Phone</option></select></label>
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.branch}</span><select name="branchId" required disabled={loading||branches.length===0} className="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm"><option value="">{loading?"Loading...":t.select}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name} — {b.city}</option>)}</select></label>
</div></section>
<section className="border-t border-zinc-100 pt-6"><div className="flex items-center gap-2"><UserRoundPlus size={17}/><h2 className="text-sm font-black uppercase tracking-wider">{t.trusted}</h2></div><div className="mt-4 flex items-center gap-2"><input id="same" type="checkbox" checked={same} onChange={e=>{const v=e.target.checked;setSame(v);if(v)setTrusted(x=>({...x,email:client.email,primaryPhone:client.primaryPhone,alternativePhone:client.alternativePhone,country:client.country,city:client.city,address:client.address,language:client.language,method:client.method}));else setTrusted(x=>({...x,email:"",primaryPhone:"",alternativePhone:"",country:"",city:"",address:"",language:"fr",method:"whatsapp"}))}} className="h-4 w-4"/><label htmlFor="same" className="text-sm font-semibold">{t.same}</label></div><input type="hidden" name="trustedSameAsClient" value={String(same)}/><div className="mt-4 grid gap-4 md:grid-cols-2">
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.name}</span><input name="trustedFullName" required value={trusted.fullName} onChange={e=>setTrustedField("fullName",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.relationship}</span><input name="trustedRelationship" className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.primary}</span><input name="trustedPrimaryPhone" required value={trusted.primaryPhone} onChange={e=>setTrustedField("primaryPhone",e.target.value)} placeholder="+243812345678" inputMode="tel" autoComplete="tel" disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.alternative}</span><input name="trustedAlternativePhone" value={trusted.alternativePhone} onChange={e=>setTrustedField("alternativePhone",e.target.value)} placeholder="+243812345678" inputMode="tel" autoComplete="tel" disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.email}</span><input name="trustedEmail" type="email" value={trusted.email} onChange={e=>setTrustedField("email",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.country}</span><input name="trustedResidencyCountry" value={trusted.country} onChange={e=>setTrustedField("country",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.city}</span><input name="trustedResidencyCity" value={trusted.city} onChange={e=>setTrustedField("city",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.address}</span><input name="trustedResidencyAddress" value={trusted.address} onChange={e=>setTrustedField("address",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.language}</span><select name="trustedPreferredLanguage" value={trusted.language} onChange={e=>setTrustedField("language",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm"><option value="fr">Français</option><option value="en">English</option><option value="pt">Português</option></select></label>
<label><span className="mb-1.5 block text-xs font-semibold">{t.method}</span><select name="trustedPreferredContactMethod" value={trusted.method} onChange={e=>setTrustedField("method",e.target.value)} disabled={same} className="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm"><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="phone">Phone</option></select></label>
<label className="md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">{t.notes}</span><textarea name="trustedNotes" rows={3} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label></div></section>
<label className="block"><span className="mb-1.5 block text-xs font-semibold">{t.notes}</span><textarea name="notes" rows={4} className="w-full rounded-xl border border-zinc-200 px-3.5 py-3 text-sm"/></label>
{state.message&&<p className={state.success?"rounded-xl bg-emerald-50 px-3.5 py-3 text-xs font-medium text-emerald-700":"rounded-xl bg-red-50 px-3.5 py-3 text-xs font-medium text-red-700"}>{state.message}</p>}
<div className="flex justify-end border-t border-zinc-100 pt-5"><button disabled={pending||loading||branches.length===0} className="inline-flex items-center gap-2 rounded-xl bg-[var(--kram-charcoal)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} {pending?t.saving:t.save}</button></div></form>}
