"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { MessageSquare, Plus, Search, Send, X } from "lucide-react";
import { sendMessage, startConversation } from "./actions";
import type { Locale } from "@/lib/i18n";

type ClientRef = { id: string; full_name: string | null; email: string | null };
type Message = { id: string; body: string; sent_at: string };
type Conversation = { id: string; subject: string | null; status: string; priority: string | null; clients: ClientRef | ClientRef[] | null; messages: Message[] };

export function CommunicationsPanel({ locale, conversations, clients }: { locale: Locale; conversations: Conversation[]; clients: ClientRef[] }) {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(conversations[0]?.id ?? null);
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  const router = useRouter();
  const labels = locale === "fr"
    ? { start: "Démarrer une conversation", client: "Client", subject: "Sujet", priority: "Priorité", opening: "Message initial", cancel: "Annuler", startAction: "Démarrer", reply: "Répondre", send: "Envoyer", select: "Sélectionner une conversation" }
    : locale === "pt"
      ? { start: "Iniciar conversa", client: "Cliente", subject: "Assunto", priority: "Prioridade", opening: "Mensagem inicial", cancel: "Cancelar", startAction: "Iniciar", reply: "Responder", send: "Enviar", select: "Selecione uma conversa" }
      : { start: "Start conversation", client: "Client", subject: "Subject", priority: "Priority", opening: "Opening message", cancel: "Cancel", startAction: "Start conversation", reply: "Reply", send: "Send", select: "Select a conversation" };
  const filtered = useMemo(() => conversations.filter((conversation) => {
    const client = Array.isArray(conversation.clients) ? conversation.clients[0] : conversation.clients;
    return !query || [client?.full_name, conversation.subject, ...conversation.messages.map((item) => item.body)].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase());
  }), [conversations, query]);
  const active = conversations.find((conversation) => conversation.id === selected);
  const activeClient = active && (Array.isArray(active.clients) ? active.clients[0] : active.clients);

  return <section className="relative grid min-h-[620px] overflow-hidden rounded-2xl border border-[var(--kram-border)] bg-white lg:grid-cols-[330px_1fr]">
    <aside className="border-b border-zinc-100 lg:border-b-0 lg:border-r"><div className="flex items-center gap-2 border-b p-4"><div className="flex flex-1 items-center gap-2 rounded-lg border bg-zinc-50 px-3 py-2"><Search size={15} className="text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search conversations..." className="w-full bg-transparent text-sm outline-none" /></div><button type="button" onClick={() => setOpen(true)} title={labels.start} className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--kram-charcoal)] text-white hover:opacity-90"><Plus size={17} /></button></div>
      <div className="divide-y divide-zinc-100">{filtered.map((conversation) => { const client = Array.isArray(conversation.clients) ? conversation.clients[0] : conversation.clients; const latest = conversation.messages[0]; return <button type="button" key={conversation.id} onClick={() => setSelected(conversation.id)} className={`block w-full px-4 py-4 text-left hover:bg-zinc-50 ${selected === conversation.id ? "bg-orange-50/60" : ""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-zinc-900">{client?.full_name ?? "Client"}</p><p className="mt-0.5 truncate text-xs text-zinc-400">{conversation.subject || "General communication"}</p></div><span className="rounded-full bg-zinc-100 px-2 py-0.5 text-[10px] font-bold uppercase text-zinc-500">{conversation.status}</span></div>{latest && <p className="mt-2 truncate text-xs text-zinc-500">{latest.body}</p>}</button>; })}{!filtered.length && <div className="p-8 text-center text-sm text-zinc-500">{query ? "No conversations match your search." : "No conversations yet. Start a conversation with a client."}</div>}</div>
    </aside>
    <main className="flex min-w-0 flex-col">{active ? <><header className="border-b border-zinc-100 p-5"><p className="text-sm font-bold">{activeClient?.full_name ?? "Client"}</p><p className="mt-1 text-xs text-zinc-400">{active.subject || "General communication"}</p></header><div className="flex-1 space-y-4 overflow-y-auto p-6">{[...active.messages].reverse().map((item) => <div key={item.id} className="max-w-2xl rounded-2xl bg-zinc-50 p-4"><p className="text-sm leading-6 text-zinc-700">{item.body}</p><p className="mt-2 text-[10px] text-zinc-400">{new Date(item.sent_at).toLocaleString()}</p></div>)}</div><form action={async (formData) => { await sendMessage(formData); setMessage(""); router.refresh(); }} className="border-t bg-zinc-50/60 p-4"><input type="hidden" name="conversationId" value={active.id} /><input type="hidden" name="visibility" value="client" /><div className="flex items-end gap-2"><textarea name="body" value={message} onChange={(event) => setMessage(event.target.value)} required rows={2} placeholder={labels.reply} className="min-w-0 flex-1 resize-none rounded-xl border border-zinc-200 bg-white px-3 py-2.5 text-sm" /><button disabled={!message.trim()} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-[var(--kram-charcoal)] px-4 py-2.5 text-xs font-bold text-white"><Send size={14} />{labels.send}</button></div></form></> : <div className="flex flex-1 items-center justify-center p-10 text-center"><div><MessageSquare size={23} className="mx-auto text-zinc-400" /><h2 className="mt-4 text-base font-bold">{labels.select}</h2><p className="mt-1 text-sm text-zinc-500">Choose a client conversation from the list.</p></div></div>}</main>
    {open && <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold text-zinc-900">{labels.start}</h2><p className="mt-1 text-xs text-zinc-500">Create the conversation and its opening message.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-100"><X size={18} /></button></div><form action={async (formData) => { const result = await startConversation(formData); if (result?.success && result.id) { setSelected(result.id); setOpen(false); router.refresh(); } }} className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold">{labels.client}</span><select name="clientId" required className="w-full rounded-xl border px-3.5 py-3 text-sm"><option value="">Select a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.full_name || "Client"}{client.email ? ` — ${client.email}` : ""}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">{labels.subject}</span><input name="subject" required placeholder="e.g. Maintenance request" className="w-full rounded-xl border px-3.5 py-3 text-sm" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">{labels.priority}</span><select name="priority" className="w-full rounded-xl border px-3.5 py-3 text-sm"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">{labels.opening}</span><textarea name="body" required rows={5} placeholder="Write the first message..." className="w-full rounded-xl border px-3.5 py-3 text-sm" /></label><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">{labels.cancel}</button><button className="rounded-xl bg-[var(--kram-charcoal)] px-4 py-2.5 text-sm font-bold text-white">{labels.startAction}</button></div></form></div></div>}
  </section>;
}
