import type { Locale } from "@/lib/i18n";

export type LegalDocument = "privacy-policy" | "terms-of-service" | "cookie-policy" | "faqs";
export type LegalSection = { heading: string; paragraphs?: string[]; bullets?: string[] };
export type LegalCopy = { title: string; intro: string; updated: string; sections: LegalSection[] };

const updated = "10 October 2026";

export const legalContent: Record<Locale, Record<LegalDocument, LegalCopy>> = {
  en: {
    "privacy-policy": {
      title: "Privacy Policy",
      intro: "How KRAM handles personal information when you enquire about our services, work with us, or use our website and client-facing tools.",
      updated,
      sections: [
        { heading: "1. Who we are", paragraphs: ["KRAM — Kore Remote Asset Management (KRAM, “we”, “us” or “our”) provides remote asset oversight and related coordination services. Our current footprint includes Luanda, Angola; Kinshasa, Democratic Republic of the Congo; and Cape Town, South Africa, and may expand as our operations grow.", "This policy describes our intended approach to personal information. The entity contracting with you, applicable local law and any signed service agreement may add specific requirements. This website policy is not a substitute for advice on the laws that apply to your circumstances."] },
        { heading: "2. Information we may collect", paragraphs: ["Depending on how you interact with KRAM, we may process:"], bullets: ["Identity and contact details you submit, such as your name, email address, telephone number and preferred contact method.", "Residence and asset details, including country, city, property or asset address, asset type and services requested.", "Enquiry content, instructions, correspondence and information you choose to provide.", "For clients, information needed to coordinate agreed work, which may include inspection findings, photographs, reports, project updates, work records, quotations, invoices, expenses, approvals and supporting documents.", "Account and technical information needed to operate a client portal, such as authentication identifiers, session data, security logs and basic device or browser information made available by the service."] },
        { heading: "3. How information reaches us", paragraphs: ["We receive information when you submit an enquiry form, communicate with us by email, telephone or messaging service, become a client, use the client portal, or provide information through a person authorised to act for you. Field updates and supporting evidence may be shared with KRAM by our operational network through established communication channels, including phone or WhatsApp."] },
        { heading: "4. Why we use information", bullets: ["To respond to enquiries and assess whether our services fit your needs.", "To prepare proposals, agree the scope of work and manage the client relationship.", "To coordinate inspections, maintenance, projects and other agreed asset oversight activities.", "To provide reports, evidence, expense visibility and updates to authorised clients.", "To operate, secure, troubleshoot and improve our website and client-facing tools.", "To prevent misuse, keep appropriate business records, resolve disputes and meet legal obligations where applicable."] },
        { heading: "5. Enquiries are not client accounts", paragraphs: ["Submitting an enquiry does not create a client account, accept a service proposal or commit you to purchase services. Enquiry information is reviewed so our team can follow up and determine possible next steps. A client relationship and any service obligations begin only when separately agreed, normally in writing."] },
        { heading: "6. Sharing and service providers", paragraphs: ["We do not sell personal information. We may share relevant information only where reasonably necessary for the purposes described in this policy, including with authorised KRAM personnel, operational coordinators, service professionals engaged for a task, technology and hosting providers, professional advisers, or public authorities where disclosure is required by law. We aim to share only information needed for the relevant task.", "KRAM may use service providers for website hosting, authentication, database storage, communications and related infrastructure. Those providers may process information on our behalf under their own service terms and security practices. Where third-party professionals are involved in work at an asset, relevant details may be shared to enable the agreed work."] },
        { heading: "7. International processing", paragraphs: ["KRAM serves owners and assets across borders, and information may be accessed or processed in a country different from your residence or the location of an asset. Applicable safeguards and requirements depend on the countries involved, the service providers used and the law that applies. We will take reasonable steps to handle information appropriately, but we do not claim that every transfer has a single universal legal basis across all jurisdictions."] },
        { heading: "8. Security and confidentiality", paragraphs: ["We use reasonable organisational and technical measures intended to protect information against unauthorised access, loss, alteration or disclosure. Access should be limited to people who need information for an authorised purpose. No website, messaging channel, storage system or internet transmission can be guaranteed completely secure; please avoid sending passwords or information that is not needed for your enquiry."] },
        { heading: "9. Retention", paragraphs: ["We keep information for as long as reasonably necessary to handle an enquiry, deliver agreed services, maintain appropriate operational and financial records, address disputes, protect our legitimate interests and meet applicable legal requirements. Retention periods vary by record type and jurisdiction. We may securely delete, anonymise or archive information when it is no longer needed, subject to applicable obligations."] },
        { heading: "10. Your choices and rights", paragraphs: ["Depending on the law applicable to you, you may have rights to request access to, correction of, deletion of, restriction of, or a copy of certain personal information, or to object to particular processing. You may also withdraw consent where processing is based on consent; this does not affect processing already carried out lawfully. Requests may require us to verify your identity and may be subject to legal exceptions.", "To make a privacy request, use the Contact Us or Submit an Enquiry link on this website and clearly state that your message concerns privacy. Do not include account passwords in your request."] },
        { heading: "11. Children", paragraphs: ["KRAM's services are designed for property owners, clients and business contacts, not for children. Please do not submit a child's personal information unless it is necessary, lawful and you are authorised to provide it."] },
        { heading: "12. Changes and contact", paragraphs: ["We may update this policy as our services, technology or legal obligations change. The updated date at the top indicates the version currently displayed. Material changes should be reviewed before the updated policy is relied upon.", "For questions or privacy requests, use the contact options available on the KRAM website. Confirmed contact details will be published there when configured."] }
      ]
    },
    "terms-of-service": {
      title: "Terms of Service",
      intro: "The basic terms for using the KRAM website and understanding how enquiries, client access and asset oversight services work.",
      updated,
      sections: [
        { heading: "1. About these terms", paragraphs: ["These terms apply to your use of the KRAM public website and its informational content. KRAM means Kore Remote Asset Management. KRAM's current footprint includes Luanda, Angola; Kinshasa, Democratic Republic of the Congo; and Cape Town, South Africa, with potential to expand internationally.", "If you enter into a separate proposal, statement of work, management mandate or service agreement with KRAM, that signed agreement will govern the specific services, fees, responsibilities, limits and service arrangements. If it conflicts with these website terms, the signed agreement controls for that engagement."] },
        { heading: "2. Website use", bullets: ["Use the website lawfully and do not attempt to disrupt, damage, probe or gain unauthorised access to it or related systems.", "Do not submit false, misleading, unlawful, abusive or malicious information.", "Do not upload malware or attempt to access another person's account, data or assets without authorisation.", "You are responsible for the accuracy of information you provide and for keeping your login credentials confidential. Notify KRAM promptly if you believe your account has been compromised."] },
        { heading: "3. Enquiries and client accounts", paragraphs: ["Submitting an enquiry is an initial request for discussion only. It does not automatically create a client account, establish an agency relationship, reserve capacity, create a contract or oblige KRAM to accept the work.", "KRAM's team may review the enquiry and contact you for clarification. Any engagement is subject to confirmation of scope, availability, pricing, responsibilities and other terms, normally in a separate written agreement. Client portal access may be issued or enabled separately and may be limited, suspended or withdrawn for security or operational reasons."] },
        { heading: "4. Services and field coordination", paragraphs: ["Depending on the agreed scope, KRAM may provide asset inspections, maintenance coordination, project or construction oversight, expense visibility, reporting and ongoing asset oversight. Specific deliverables, schedules, budgets, service levels and approval requirements must be agreed for each engagement.", "KRAM coordinates work and communicates information to help clients make informed decisions. The actual execution of repairs, construction, inspections or specialist work may be carried out by third-party professionals or contractors. Unless expressly agreed in writing, KRAM does not represent that every contractor is an employee of KRAM, nor that a particular outcome, completion date, cost or asset condition can be guaranteed.", "Clients remain responsible for decisions and approvals reserved to them under the applicable service agreement, including approval of proposed works or expenses where required. KRAM is not an emergency-response service unless an applicable written agreement expressly says otherwise."] },
        { heading: "5. Estimates, reports and decisions", paragraphs: ["Reports, photographs, observations, estimates and updates reflect information available at the time and the agreed scope of work. An inspection is not necessarily a structural survey, legal title review, valuation, environmental assessment or specialist certification unless the written scope expressly includes it and the relevant qualified professional is engaged.", "Costs and timelines may change because of site conditions, availability, supply, weather, permissions, scope changes or other circumstances. KRAM will communicate material changes as reasonably practicable under the agreed service arrangements. Clients should not treat general website content as a substitute for professional legal, tax, engineering or financial advice."] },
        { heading: "6. Fees and payment", paragraphs: ["Fees, payment schedules, taxes, third-party costs, expense approval limits and any cancellation or refund arrangements are set out in the relevant proposal or written service agreement. Nothing on this website establishes a price or payment obligation unless explicitly confirmed in writing for your engagement. Do not pay an individual or third party claiming to represent KRAM unless the payment instructions have been verified through an authorised KRAM channel."] },
        { heading: "7. Intellectual property", paragraphs: ["Unless otherwise stated, the website's text, branding, design and original materials belong to KRAM or are used with permission. You may view and use them for personal or internal business evaluation. You may not reproduce, republish, commercially exploit or modify them in a way that infringes rights or misrepresents KRAM without prior permission. Client-specific reports and deliverables are governed by the relevant service agreement."] },
        { heading: "8. Third-party services and links", paragraphs: ["The website or our service workflows may refer to third-party tools, messaging services or professionals. Those parties may have separate terms and privacy practices. KRAM is not responsible for independent third-party websites or services that it does not control. Use them with appropriate care and review their terms where relevant."] },
        { heading: "9. Availability and disclaimers", paragraphs: ["We aim to keep the website useful and available, but do not guarantee uninterrupted, error-free or permanently available access. Website content is general information and may not describe every service or location in which KRAM can operate. To the extent permitted by applicable law, the website is provided without warranties not expressly stated in a written agreement. Nothing in these terms excludes a right or liability that cannot lawfully be excluded."] },
        { heading: "10. Liability", paragraphs: ["To the extent permitted by applicable law, KRAM is not liable for indirect or consequential losses arising solely from use of this informational website, interruption of access, or reliance on general website content. Any liability connected with contracted services is governed by the applicable written agreement and mandatory law. Nothing here excludes liability that cannot lawfully be excluded, including any non-waivable consumer rights."] },
        { heading: "11. Suspension, changes and governing law", paragraphs: ["We may change, suspend or remove website features for maintenance, security, legal or operational reasons. We may update these terms by publishing a revised version with an updated date.", "The governing law and dispute process for a specific service engagement should be stated in its written agreement. These website terms do not nominate a single governing law for every country in which KRAM or its clients may operate."] },
        { heading: "12. Contact", paragraphs: ["For questions about these terms, use the Contact Us or Submit an Enquiry link on the KRAM website. Confirmed contact details will be published there when configured."] }
      ]
    },
    "cookie-policy": {
      title: "Cookie Policy",
      intro: "What cookies and similar technologies may be used when you visit KRAM's website or access client-facing tools.",
      updated,
      sections: [
        { heading: "1. What cookies are", paragraphs: ["Cookies are small text files stored by a browser. Similar technologies, such as local storage or session identifiers, can help a website remember a session, maintain security or understand technical behaviour. This policy covers those technologies in general; the exact technologies in use can change as the website evolves."] },
        { heading: "2. Essential operation", paragraphs: ["KRAM's client-facing tools may rely on essential cookies or similar storage for functions such as authentication, maintaining a secure session, protecting forms and remembering technical preferences. If you sign in to a client portal, some storage may be necessary for the portal to work and to protect your account. Blocking all storage may prevent some features from functioning."] },
        { heading: "3. Analytics and advertising", paragraphs: ["This policy does not claim that KRAM currently uses advertising cookies or third-party analytics cookies. If non-essential analytics, advertising or personalisation technologies are introduced, this policy should be updated to identify their purposes and providers, and any consent or opt-out controls required by applicable law should be implemented before they are used."] },
        { heading: "4. Third-party services", paragraphs: ["The website and client tools may depend on third-party infrastructure, such as hosting or authentication providers. Those services may set or use technologies necessary to deliver their functionality. The precise providers and technologies should be verified against the deployed configuration and the providers' current documentation."] },
        { heading: "5. Managing cookies", paragraphs: ["Most browsers allow you to review, block or delete cookies through browser settings. Controls vary by browser and device. Removing essential session cookies may sign you out or affect site features. Browser controls do not necessarily remove every form of local storage."] },
        { heading: "6. Changes and contact", paragraphs: ["We may update this policy when the website or its technologies change. The updated date indicates the version currently displayed. For questions, use the Contact Us or Submit an Enquiry link on the KRAM website."] }
      ]
    },
    faqs: {
      title: "Frequently Asked Questions",
      intro: "A practical guide to how KRAM helps owners oversee assets from a distance.",
      updated,
      sections: [
        { heading: "What is KRAM?", paragraphs: ["KRAM — Kore Remote Asset Management — helps owners gain clearer oversight of property and related assets through inspections, maintenance coordination, project oversight, expense visibility and ongoing reporting."] },
        { heading: "Who is KRAM for?", paragraphs: ["KRAM is designed for owners and clients who need reliable information and practical coordination for an asset they cannot always oversee in person, including people living abroad or managing assets across locations."] },
        { heading: "Where does KRAM operate?", paragraphs: ["Our current footprint includes Luanda, Angola; Kinshasa, Democratic Republic of the Congo; and Cape Town, South Africa. KRAM is intended to grow internationally; a location appearing here does not mean every service is available in every area. Please submit an enquiry to confirm coverage for your asset."] },
        { heading: "What services can I request?", paragraphs: ["Depending on location and scope, you can ask about asset inspections, maintenance coordination, project or construction monitoring, visibility into costs and expenses, and ongoing asset oversight. The precise deliverables are agreed before work begins."] },
        { heading: "How do I get started?", paragraphs: ["Submit an enquiry and tell us about yourself, where you live, the asset's location and type, and the support you need. You can include up to 20 assets in one enquiry. Our team reviews the information and follows up about potential next steps."] },
        { heading: "Does submitting an enquiry create a client account?", paragraphs: ["No. An enquiry is a request for discussion only. It does not create a client account or commit you to buy services. KRAM reviews the request first; client onboarding and any service agreement happen separately."] },
        { heading: "What happens after I submit an enquiry?", paragraphs: ["The KRAM team reviews the details you provide and may contact you using your preferred method to clarify your needs, confirm service availability and discuss possible scope, timing and pricing. Sending an enquiry does not guarantee that KRAM will accept the engagement."] },
        { heading: "Can KRAM manage multiple properties or assets?", paragraphs: ["You can describe up to 20 assets in one initial enquiry. If you have more assets or a complex portfolio, tell us in the details field so the team can discuss a suitable onboarding process."] },
        { heading: "How does KRAM keep me informed?", paragraphs: ["The intended approach centres on clear communication and evidence-based updates, which may include inspection findings, photographs, reports, project progress, work records and expense information as agreed for your engagement. The exact reporting cadence and deliverables depend on the written scope."] },
        { heading: "Who carries out work at my property?", paragraphs: ["KRAM coordinates and oversees agreed activities. Depending on the task, field work may be performed by independent technicians or specialist service providers. The responsible parties, approvals, quality checks and any warranties should be confirmed in the relevant proposal or service agreement."] },
        { heading: "Can I approve expenses and works?", paragraphs: ["Approval steps and spending limits should be agreed for your engagement. Where the agreed workflow requires your approval, the team should seek it before proceeding with the relevant cost or work, except where a separate written arrangement says otherwise."] },
        { heading: "Does KRAM provide emergency response?", paragraphs: ["Do not assume that KRAM provides 24/7 emergency response. Availability, escalation contacts and urgent-work procedures must be explicitly confirmed in your service agreement. For immediate danger, contact the appropriate local emergency services."] },
        { heading: "How are fees determined?", paragraphs: ["Fees depend on the asset, location, requested services, scope, frequency, travel and third-party costs. KRAM will discuss the applicable proposal and payment terms before a service engagement is confirmed. No fee is created simply by submitting an enquiry."] },
        { heading: "How is my information handled?", paragraphs: ["KRAM uses enquiry and client information to respond to requests, coordinate agreed services, provide updates, administer access and maintain appropriate records. See the Privacy Policy for more information about categories of information, sharing, retention and your choices."] },
        { heading: "How do I contact KRAM?", paragraphs: ["Use the Contact Us or Submit an Enquiry link on this website. Available contact methods may vary by location and will be displayed when confirmed."] }
      ]
    }
  },
  fr: {
    "privacy-policy": {
      title: "Politique de confidentialité",
      intro: "Comment KRAM traite les données personnelles lorsque vous nous contactez, travaillez avec nous ou utilisez notre site et nos outils destinés aux clients.",
      updated,
      sections: [
        { heading: "1. Qui sommes-nous ?", paragraphs: ["KRAM — Kore Remote Asset Management (« KRAM », « nous ») propose le suivi à distance des actifs et la coordination de services associés. Notre présence actuelle comprend Luanda, en Angola ; Kinshasa, en République démocratique du Congo ; et Cape Town, en Afrique du Sud. Notre activité peut s'étendre à d'autres régions.", "Cette politique décrit notre approche prévue du traitement des données personnelles. Le contrat applicable, l'entité qui vous fournit le service et le droit local peuvent imposer des exigences supplémentaires. Ce document ne remplace pas un conseil juridique adapté à votre situation."] },
        { heading: "2. Données susceptibles d'être collectées", bullets: ["Identité et coordonnées que vous fournissez : nom, adresse e-mail, téléphone et moyen de contact préféré.", "Informations sur votre résidence et vos actifs : pays, ville, adresse, type d'actif et services demandés.", "Contenu de votre demande, instructions, échanges et informations que vous choisissez de communiquer.", "Pour les clients, informations nécessaires à la coordination du travail convenu : constats d'inspection, photos, rapports, avancement de projets, travaux, devis, factures, dépenses, validations et documents justificatifs.", "Données de compte et techniques nécessaires au portail client, comme les identifiants d'authentification, les données de session, les journaux de sécurité et certaines informations sur l'appareil ou le navigateur."] },
        { heading: "3. Comment nous recevons ces données", paragraphs: ["Nous recevons des informations lorsque vous envoyez une demande, communiquez avec nous par e-mail, téléphone ou messagerie, devenez client, utilisez le portail ou nous transmettez des données par l'intermédiaire d'une personne autorisée. Les comptes rendus du terrain et les justificatifs peuvent nous parvenir par les canaux habituels, notamment téléphone ou WhatsApp."] },
        { heading: "4. Pourquoi nous les utilisons", bullets: ["Répondre aux demandes et évaluer si nos services correspondent à vos besoins.", "Préparer des propositions, définir le périmètre et gérer la relation client.", "Coordonner les inspections, la maintenance, les projets et les autres activités convenues.", "Fournir aux clients autorisés des rapports, éléments de preuve, informations sur les dépenses et mises à jour.", "Exploiter, sécuriser, dépanner et améliorer le site et les outils clients.", "Prévenir les abus, tenir les dossiers professionnels appropriés, résoudre les litiges et respecter les obligations légales applicables."] },
        { heading: "5. Une demande ne crée pas un compte client", paragraphs: ["L'envoi d'une demande ne crée pas de compte client, n'accepte pas une proposition de service et ne vous oblige pas à acheter une prestation. L'équipe examine la demande pour vous répondre et envisager les étapes suivantes. La relation client et les obligations de service ne commencent qu'après un accord séparé, généralement écrit."] },
        { heading: "6. Partage et prestataires", paragraphs: ["Nous ne vendons pas les données personnelles. Nous pouvons partager les informations pertinentes lorsque cela est raisonnablement nécessaire avec le personnel KRAM autorisé, les coordinateurs opérationnels, les professionnels mobilisés pour une tâche, les prestataires techniques, les conseillers professionnels ou les autorités lorsque la loi l'exige. Nous cherchons à limiter le partage aux informations utiles à la tâche concernée.", "KRAM peut utiliser des prestataires d'hébergement, d'authentification, de stockage, de communication et d'infrastructure. Ils peuvent traiter des données pour notre compte selon leurs conditions et pratiques de sécurité. Les informations nécessaires peuvent être transmises aux professionnels intervenant sur un actif pour permettre le travail convenu."] },
        { heading: "7. Traitement international", paragraphs: ["KRAM accompagne des propriétaires et des actifs dans plusieurs pays. Les données peuvent donc être consultées ou traitées dans un pays différent de votre résidence ou de l'emplacement de l'actif. Les garanties applicables dépendent des pays concernés, des prestataires et du droit applicable. Nous prenons des mesures raisonnables sans prétendre qu'une base juridique unique s'applique à tous les transferts et territoires."] },
        { heading: "8. Sécurité et confidentialité", paragraphs: ["Nous mettons en place des mesures organisationnelles et techniques raisonnables visant à protéger les données contre l'accès non autorisé, la perte, l'altération ou la divulgation. L'accès doit être limité aux personnes ayant un besoin autorisé. Aucun site, canal de messagerie ou système de stockage ne peut garantir une sécurité absolue ; évitez de transmettre des mots de passe ou des données inutiles."] },
        { heading: "9. Conservation", paragraphs: ["Nous conservons les données pendant une durée raisonnablement nécessaire pour traiter une demande, fournir les services convenus, tenir les dossiers opérationnels et financiers appropriés, gérer les litiges, protéger nos intérêts légitimes et respecter les obligations légales applicables. Les durées varient selon les données et les juridictions. Les données devenues inutiles peuvent être supprimées de façon sécurisée, anonymisées ou archivées, sous réserve des obligations applicables."] },
        { heading: "10. Vos choix et droits", paragraphs: ["Selon la loi applicable, vous pouvez disposer de droits d'accès, de rectification, de suppression, de limitation, de copie ou d'opposition au traitement de certaines données. Vous pouvez aussi retirer un consentement lorsque le traitement repose sur celui-ci, sans remettre en cause les traitements licites antérieurs. Une vérification d'identité et certaines exceptions légales peuvent s'appliquer.", "Pour exercer vos droits, utilisez le lien Contact ou Envoyer une demande du site KRAM en précisant qu'il s'agit d'une demande relative à la confidentialité. N'envoyez pas votre mot de passe."] },
        { heading: "11. Enfants", paragraphs: ["Les services KRAM sont destinés aux propriétaires, clients et contacts professionnels, et non aux enfants. Ne transmettez pas les données personnelles d'un enfant sauf si cela est nécessaire, licite et que vous êtes autorisé à le faire."] },
        { heading: "12. Modifications et contact", paragraphs: ["Nous pouvons actualiser cette politique selon l'évolution de nos services, technologies ou obligations. La date indiquée en haut correspond à la version affichée. Toute modification importante doit être examinée avant de se fier à la nouvelle version.", "Pour toute question ou demande relative à la confidentialité, utilisez les options de contact disponibles sur le site KRAM. Les coordonnées confirmées y seront publiées lorsqu'elles seront configurées."] }
      ]
    },
    "terms-of-service": {
      title: "Conditions d'utilisation",
      intro: "Les règles de base concernant l'utilisation du site KRAM, les demandes de service, l'accès client et le suivi des actifs.",
      updated,
      sections: [
        { heading: "1. Objet des conditions", paragraphs: ["Les présentes conditions s'appliquent à l'utilisation du site public et de son contenu informatif. KRAM signifie Kore Remote Asset Management. Notre présence actuelle comprend Luanda, en Angola ; Kinshasa, en République démocratique du Congo ; et Cape Town, en Afrique du Sud, avec une possibilité d'expansion internationale.", "Si vous concluez une proposition, un cahier des charges, un mandat de gestion ou un contrat de service distinct avec KRAM, cet accord signé régit le périmètre, les frais, les responsabilités, les limites et les modalités propres à la prestation. En cas de conflit, l'accord signé prévaut pour cette mission."] },
        { heading: "2. Utilisation du site", bullets: ["Utilisez le site légalement et ne tentez pas de le perturber, de l'endommager ou d'accéder sans autorisation aux systèmes associés.", "Ne transmettez pas d'informations fausses, trompeuses, illicites, abusives ou malveillantes.", "Ne téléversez aucun logiciel malveillant et ne tentez pas d'accéder au compte, aux données ou aux actifs d'autrui sans autorisation.", "Vous êtes responsable de l'exactitude des informations fournies et de la confidentialité de vos identifiants. Informez rapidement KRAM si vous pensez que votre compte a été compromis."] },
        { heading: "3. Demandes et comptes clients", paragraphs: ["Une demande constitue uniquement une première prise de contact. Elle ne crée pas automatiquement un compte client, un contrat, une relation de représentation, une réservation de capacité ni une obligation pour KRAM d'accepter la mission.", "L'équipe peut examiner la demande et solliciter des précisions. Toute mission dépend de la confirmation du périmètre, de la disponibilité, du prix, des responsabilités et des autres conditions, généralement dans un accord écrit distinct. L'accès au portail client peut être accordé séparément et limité, suspendu ou retiré pour des raisons de sécurité ou d'exploitation."] },
        { heading: "4. Services et coordination sur le terrain", paragraphs: ["Selon le périmètre convenu, KRAM peut proposer des inspections d'actifs, la coordination de maintenance, le suivi de projets ou de construction, la visibilité des dépenses, des rapports et un suivi continu. Les livrables, calendriers, budgets, niveaux de service et validations doivent être convenus pour chaque mission.", "KRAM coordonne les travaux et communique des informations pour aider les clients à prendre des décisions éclairées. Les réparations, travaux de construction, inspections ou tâches spécialisées peuvent être exécutés par des professionnels ou prestataires tiers. Sauf accord écrit contraire, KRAM ne prétend pas que chaque intervenant est salarié de KRAM ni qu'un résultat, une date, un coût ou un état d'actif particulier est garanti.", "Les clients restent responsables des décisions et validations qui leur incombent en vertu du contrat, notamment l'approbation des travaux ou dépenses lorsque celle-ci est requise. KRAM n'est pas un service d'urgence, sauf mention expresse dans un accord écrit applicable."] },
        { heading: "5. Estimations, rapports et décisions", paragraphs: ["Les rapports, photos, observations, estimations et mises à jour reflètent les informations disponibles au moment concerné et le périmètre convenu. Une inspection ne constitue pas nécessairement une expertise structurelle, une vérification de titre, une évaluation, un audit environnemental ou une certification spécialisée, sauf inclusion expresse dans le périmètre écrit et intervention du professionnel qualifié requis.", "Les coûts et délais peuvent évoluer selon l'état du site, la disponibilité, les approvisionnements, la météo, les autorisations, les changements de périmètre ou d'autres circonstances. KRAM communiquera les changements importants dans la mesure raisonnablement possible. Le contenu général du site ne remplace pas un conseil juridique, fiscal, technique ou financier professionnel."] },
        { heading: "6. Frais et paiement", paragraphs: ["Les honoraires, échéances de paiement, taxes, coûts de tiers, limites de validation des dépenses et modalités d'annulation ou de remboursement sont définis dans la proposition ou le contrat écrit applicable. Le site ne fixe aucun prix ni obligation de paiement sans confirmation écrite explicite pour votre mission. Ne payez pas une personne prétendant représenter KRAM sans avoir vérifié les instructions par un canal autorisé."] },
        { heading: "7. Propriété intellectuelle", paragraphs: ["Sauf indication contraire, les textes, la marque, le design et les contenus originaux du site appartiennent à KRAM ou sont utilisés avec autorisation. Vous pouvez les consulter pour votre usage personnel ou pour une évaluation interne. Toute reproduction, publication, exploitation commerciale ou modification portant atteinte aux droits ou présentant faussement KRAM nécessite une autorisation préalable. Les rapports et livrables propres au client sont régis par le contrat applicable."] },
        { heading: "8. Services et liens tiers", paragraphs: ["Le site ou nos processus peuvent renvoyer vers des outils, services de messagerie ou professionnels tiers. Ces parties peuvent avoir leurs propres conditions et pratiques de confidentialité. KRAM ne contrôle pas les sites ou services indépendants de tiers et n'en est pas responsable."] },
        { heading: "9. Disponibilité et exclusions", paragraphs: ["Nous cherchons à maintenir un site utile et disponible, sans garantir un accès continu, sans erreur ou permanent. Le contenu du site est général et ne décrit pas nécessairement tous les services ou toutes les zones où KRAM peut intervenir. Dans la mesure permise par la loi, le site est fourni sans garantie autre que celle expressément prévue dans un accord écrit. Rien dans ces conditions n'exclut un droit ou une responsabilité qui ne peut légalement être exclu.", "Dans la mesure permise par la loi, KRAM n'est pas responsable des pertes indirectes découlant uniquement de l'utilisation de ce site informatif, d'une interruption d'accès ou de la confiance accordée au contenu général. La responsabilité liée aux services contractuels relève de l'accord applicable et du droit impératif. Les responsabilités qui ne peuvent légalement être exclues restent applicables."] },
        { heading: "10. Suspension, modifications et droit applicable", paragraphs: ["Nous pouvons modifier, suspendre ou supprimer des fonctionnalités pour des raisons de maintenance, de sécurité, de droit ou d'exploitation. Les conditions peuvent être mises à jour par publication d'une nouvelle version avec une date révisée.", "Le droit applicable et la procédure de règlement des différends d'une mission doivent être indiqués dans son accord écrit. Ces conditions du site ne désignent pas un droit unique pour tous les pays où KRAM ou ses clients peuvent exercer leurs activités."] },
        { heading: "11. Contact", paragraphs: ["Pour toute question sur ces conditions, utilisez les liens Contact ou Envoyer une demande du site KRAM. Les coordonnées confirmées seront publiées lorsqu'elles seront configurées."] }
      ]
    },
    "cookie-policy": {
      title: "Politique relative aux cookies",
      intro: "Comment les cookies et technologies similaires peuvent être utilisés sur le site KRAM et dans les outils destinés aux clients.",
      updated,
      sections: [
        { heading: "1. Que sont les cookies ?", paragraphs: ["Les cookies sont de petits fichiers texte enregistrés par un navigateur. D'autres technologies, comme le stockage local ou les identifiants de session, peuvent aider le site à mémoriser une session, assurer la sécurité ou comprendre son fonctionnement technique. Cette politique décrit ces technologies de manière générale ; leur utilisation précise peut évoluer."] },
        { heading: "2. Fonctionnement essentiel", paragraphs: ["Les outils clients de KRAM peuvent utiliser des cookies essentiels ou un stockage similaire pour l'authentification, le maintien d'une session sécurisée, la protection des formulaires et la mémorisation de préférences techniques. Lors d'une connexion au portail client, certains éléments de stockage peuvent être indispensables au fonctionnement et à la sécurité du compte. Le blocage de tout stockage peut empêcher certaines fonctionnalités de fonctionner."] },
        { heading: "3. Analyse d'audience et publicité", paragraphs: ["Cette politique n'affirme pas que KRAM utilise actuellement des cookies publicitaires ou d'analyse tiers. Si des technologies non essentielles d'analyse, de publicité ou de personnalisation sont ajoutées, cette politique devra identifier leurs finalités et fournisseurs, et les mécanismes de consentement ou de refus exigés par la loi applicable devront être mis en place avant leur utilisation."] },
        { heading: "4. Services tiers", paragraphs: ["Le site et les outils clients peuvent dépendre d'infrastructures tierces, comme l'hébergement ou l'authentification. Ces services peuvent utiliser des technologies nécessaires à leur fonctionnement. Les fournisseurs et technologies exacts doivent être vérifiés dans la configuration déployée et dans la documentation actuelle des prestataires."] },
        { heading: "5. Gérer les cookies", paragraphs: ["La plupart des navigateurs permettent de consulter, bloquer ou supprimer les cookies dans leurs paramètres. Les options varient selon le navigateur et l'appareil. La suppression des cookies de session essentiels peut vous déconnecter ou affecter certaines fonctions. Les commandes du navigateur ne suppriment pas nécessairement toutes les formes de stockage local."] },
        { heading: "6. Modifications et contact", paragraphs: ["Nous pouvons actualiser cette politique lorsque le site ou ses technologies changent. La date indiquée correspond à la version affichée. Pour toute question, utilisez les liens Contact ou Envoyer une demande du site KRAM."] }
      ]
    },
    faqs: {
      title: "Questions fréquentes",
      intro: "Un guide pratique pour comprendre comment KRAM aide les propriétaires à suivre leurs actifs à distance.",
      updated,
      sections: [
        { heading: "Qu'est-ce que KRAM ?", paragraphs: ["KRAM — Kore Remote Asset Management — aide les propriétaires à mieux suivre leurs biens immobiliers et actifs grâce aux inspections, à la coordination de maintenance, au suivi de projets, à la visibilité des dépenses et aux rapports continus."] },
        { heading: "À qui s'adresse KRAM ?", paragraphs: ["KRAM s'adresse aux propriétaires et clients qui ont besoin d'informations fiables et d'une coordination pratique pour un actif qu'ils ne peuvent pas toujours superviser sur place, notamment les personnes vivant à l'étranger ou gérant des actifs dans plusieurs régions."] },
        { heading: "Où KRAM intervient-il ?", paragraphs: ["Notre présence actuelle comprend Luanda, en Angola ; Kinshasa, en République démocratique du Congo ; et Cape Town, en Afrique du Sud. KRAM a vocation à se développer à l'international ; la présence d'une ville ne signifie pas que tous les services y sont disponibles. Envoyez une demande pour confirmer la couverture de votre actif."] },
        { heading: "Quels services puis-je demander ?", paragraphs: ["Selon le lieu et le périmètre, vous pouvez demander une inspection d'actif, la coordination de maintenance, le suivi de projet ou de construction, la visibilité des coûts et dépenses, ou le suivi continu d'un actif. Les livrables précis sont convenus avant le début du travail."] },
        { heading: "Comment commencer ?", paragraphs: ["Envoyez une demande en indiquant vos coordonnées, votre lieu de résidence, l'emplacement et le type d'actif, ainsi que l'aide souhaitée. Vous pouvez inclure jusqu'à 20 actifs dans une même demande. Notre équipe l'examinera et vous contactera pour discuter des étapes possibles."] },
        { heading: "Une demande crée-t-elle un compte client ?", paragraphs: ["Non. Une demande sert uniquement à engager la discussion. Elle ne crée pas de compte client et ne vous oblige pas à acheter un service. L'équipe examine d'abord votre demande ; l'intégration client et tout contrat de service sont distincts."] },
        { heading: "Que se passe-t-il après l'envoi ?", paragraphs: ["L'équipe KRAM examine les informations et peut vous contacter par le moyen choisi afin de préciser vos besoins, confirmer la disponibilité du service et discuter du périmètre, du calendrier et du prix. L'envoi d'une demande ne garantit pas que KRAM acceptera la mission."] },
        { heading: "KRAM peut-il suivre plusieurs biens ?", paragraphs: ["Vous pouvez décrire jusqu'à 20 actifs dans une demande initiale. Pour un portefeuille plus important ou complexe, indiquez-le dans le champ de détails afin que l'équipe puisse discuter d'une procédure d'intégration adaptée."] },
        { heading: "Comment serai-je informé ?", paragraphs: ["L'approche repose sur une communication claire et des mises à jour étayées par des éléments concrets, pouvant inclure constats d'inspection, photos, rapports, avancement de projets, dossiers de travaux et informations sur les dépenses selon le contrat. La fréquence et les livrables dépendent du périmètre écrit."] },
        { heading: "Qui réalise les travaux sur mon bien ?", paragraphs: ["KRAM coordonne et suit les activités convenues. Selon la tâche, le travail sur le terrain peut être effectué par des techniciens indépendants ou des prestataires spécialisés. Les responsabilités, validations, contrôles qualité et garanties éventuelles doivent être précisés dans la proposition ou le contrat."] },
        { heading: "Puis-je approuver les travaux et dépenses ?", paragraphs: ["Les étapes de validation et les plafonds de dépenses doivent être convenus pour votre mission. Lorsque le processus prévoit votre approbation, l'équipe doit la demander avant d'engager le coût ou le travail concerné, sauf accord écrit distinct."] },
        { heading: "KRAM propose-t-il un service d'urgence ?", paragraphs: ["Ne supposez pas que KRAM assure une intervention d'urgence 24 h/24 et 7 j/7. La disponibilité, les contacts d'escalade et les procédures urgentes doivent être expressément confirmés dans le contrat. En cas de danger immédiat, contactez les services d'urgence locaux compétents."] },
        { heading: "Comment les frais sont-ils fixés ?", paragraphs: ["Les frais dépendent de l'actif, de son emplacement, des services demandés, du périmètre, de la fréquence, des déplacements et des coûts de tiers. KRAM discutera de la proposition et des modalités de paiement avant de confirmer une mission. Une simple demande n'entraîne aucun frais."] },
        { heading: "Comment mes informations sont-elles utilisées ?", paragraphs: ["KRAM utilise les informations de demande et de client pour répondre, coordonner les services convenus, fournir des mises à jour, gérer les accès et conserver les dossiers appropriés. Consultez la Politique de confidentialité pour plus de détails sur les données, le partage, la conservation et vos choix."] },
        { heading: "Comment contacter KRAM ?", paragraphs: ["Utilisez les liens Contact ou Envoyer une demande du site. Les moyens de contact disponibles peuvent varier selon le lieu et seront affichés lorsqu'ils seront confirmés."] }
      ]
    }
  },
  pt: {
    "privacy-policy": {
      title: "Política de Privacidade",
      intro: "Como a KRAM trata dados pessoais quando solicita os nossos serviços, trabalha connosco ou utiliza o website e as ferramentas destinadas aos clientes.",
      updated,
      sections: [
        { heading: "1. Quem somos", paragraphs: ["A KRAM — Kore Remote Asset Management («KRAM», «nós») presta serviços de acompanhamento remoto de ativos e coordenação relacionada. A nossa presença atual inclui Luanda, Angola; Kinshasa, República Democrática do Congo; e Cape Town, África do Sul, podendo expandir-se à medida que a operação cresce.", "Esta política descreve a nossa abordagem prevista ao tratamento de dados pessoais. O contrato aplicável, a entidade que presta o serviço e a legislação local podem estabelecer requisitos adicionais. Este documento não substitui aconselhamento jurídico adequado à sua situação."] },
        { heading: "2. Dados que podemos recolher", bullets: ["Identificação e contactos fornecidos por si, como nome, e-mail, telefone e método de contacto preferido.", "Dados de residência e dos ativos, incluindo país, cidade, morada, tipo de ativo e serviços pretendidos.", "Conteúdo do pedido, instruções, comunicações e informações que decida partilhar.", "Para clientes, dados necessários para coordenar o trabalho acordado, que podem incluir constatações de inspeção, fotografias, relatórios, atualizações de projetos, registos de trabalho, orçamentos, faturas, despesas, aprovações e documentos de suporte.", "Dados de conta e técnicos necessários ao portal do cliente, como identificadores de autenticação, dados de sessão, registos de segurança e algumas informações do dispositivo ou navegador."] },
        { heading: "3. Como recebemos os dados", paragraphs: ["Recebemos dados quando envia um pedido, comunica connosco por e-mail, telefone ou mensagens, se torna cliente, utiliza o portal ou fornece informações através de alguém autorizado a agir em seu nome. Atualizações do terreno e documentos de suporte podem ser partilhados com a KRAM pelos canais habituais, incluindo telefone ou WhatsApp."] },
        { heading: "4. Para que utilizamos os dados", bullets: ["Responder a pedidos e avaliar se os nossos serviços correspondem às suas necessidades.", "Preparar propostas, acordar o âmbito e gerir a relação com o cliente.", "Coordenar inspeções, manutenção, projetos e outras atividades acordadas de acompanhamento de ativos.", "Fornecer relatórios, evidências, visibilidade de despesas e atualizações a clientes autorizados.", "Operar, proteger, resolver problemas e melhorar o website e as ferramentas do cliente.", "Prevenir utilização indevida, manter registos comerciais adequados, resolver disputas e cumprir obrigações legais aplicáveis."] },
        { heading: "5. Um pedido não cria uma conta de cliente", paragraphs: ["Enviar um pedido não cria uma conta de cliente, não aceita uma proposta de serviço e não o obriga a comprar serviços. A equipa analisa o pedido para responder e considerar os próximos passos. A relação com o cliente e as obrigações de serviço só começam após acordo separado, normalmente por escrito."] },
        { heading: "6. Partilha e prestadores de serviços", paragraphs: ["Não vendemos dados pessoais. Podemos partilhar informações relevantes quando razoavelmente necessário com pessoal autorizado da KRAM, coordenadores operacionais, profissionais envolvidos numa tarefa, fornecedores tecnológicos, consultores profissionais ou autoridades quando a lei o exigir. Procuramos limitar a partilha aos dados necessários para a tarefa.", "A KRAM pode utilizar fornecedores de alojamento, autenticação, armazenamento de bases de dados, comunicações e infraestrutura. Esses fornecedores podem tratar dados em nosso nome segundo os seus termos e práticas de segurança. Os dados necessários podem ser partilhados com profissionais que executem trabalhos no ativo para permitir a prestação acordada."] },
        { heading: "7. Tratamento internacional", paragraphs: ["A KRAM trabalha com proprietários e ativos em diferentes países. Por isso, os dados podem ser acedidos ou tratados num país diferente do país onde reside ou onde se encontra o ativo. As salvaguardas aplicáveis dependem dos países envolvidos, dos fornecedores e da legislação aplicável. Tomaremos medidas razoáveis, sem afirmar que existe uma única base jurídica universal para todas as transferências e jurisdições."] },
        { heading: "8. Segurança e confidencialidade", paragraphs: ["Utilizamos medidas organizacionais e técnicas razoáveis destinadas a proteger os dados contra acesso não autorizado, perda, alteração ou divulgação. O acesso deve limitar-se às pessoas que necessitam dos dados para uma finalidade autorizada. Nenhum website, canal de mensagens ou sistema de armazenamento pode garantir segurança absoluta; evite enviar palavras-passe ou informações desnecessárias."] },
        { heading: "9. Conservação", paragraphs: ["Conservamos os dados durante o período razoavelmente necessário para tratar um pedido, prestar os serviços acordados, manter registos operacionais e financeiros adequados, resolver disputas, proteger interesses legítimos e cumprir obrigações legais aplicáveis. Os prazos variam conforme o tipo de registo e a jurisdição. Quando já não forem necessários, os dados poderão ser eliminados de forma segura, anonimizados ou arquivados, respeitando as obrigações aplicáveis."] },
        { heading: "10. As suas opções e direitos", paragraphs: ["Dependendo da legislação aplicável, poderá ter direito a solicitar acesso, correção, eliminação, limitação, cópia ou oposição ao tratamento de determinados dados pessoais. Poderá também retirar o consentimento quando o tratamento se basear nele, sem afetar o tratamento lícito já realizado. Podemos precisar de confirmar a sua identidade e aplicar-se-ão as exceções legais pertinentes.", "Para exercer os seus direitos, utilize os links Contactar ou Enviar pedido no website da KRAM e indique que a mensagem diz respeito à privacidade. Não inclua a sua palavra-passe."] },
        { heading: "11. Crianças", paragraphs: ["Os serviços da KRAM destinam-se a proprietários, clientes e contactos profissionais, não a crianças. Não envie dados pessoais de uma criança salvo se for necessário, legal e estiver autorizado a fazê-lo."] },
        { heading: "12. Alterações e contacto", paragraphs: ["Podemos atualizar esta política à medida que os serviços, tecnologias ou obrigações legais mudem. A data no início indica a versão atualmente apresentada. Alterações relevantes devem ser revistas antes de confiar na nova versão.", "Para dúvidas ou pedidos de privacidade, utilize as opções de contacto disponíveis no website da KRAM. Os contactos confirmados serão publicados quando estiverem configurados."] }
      ]
    },
    "terms-of-service": {
      title: "Termos de Serviço",
      intro: "As condições básicas de utilização do website da KRAM e informações sobre pedidos, acesso do cliente e acompanhamento de ativos.",
      updated,
      sections: [
        { heading: "1. Sobre estes termos", paragraphs: ["Estes termos aplicam-se à utilização do website público da KRAM e do seu conteúdo informativo. KRAM significa Kore Remote Asset Management. A nossa presença atual inclui Luanda, Angola; Kinshasa, República Democrática do Congo; e Cape Town, África do Sul, com possibilidade de expansão internacional.", "Se celebrar uma proposta, âmbito de trabalho, mandato de gestão ou contrato de serviços separado com a KRAM, esse acordo assinado regerá os serviços específicos, honorários, responsabilidades, limites e condições. Em caso de conflito, o acordo assinado prevalece para esse serviço."] },
        { heading: "2. Utilização do website", bullets: ["Utilize o website legalmente e não tente interromper, danificar, testar ou obter acesso não autorizado ao website ou aos sistemas relacionados.", "Não envie informações falsas, enganosas, ilícitas, abusivas ou maliciosas.", "Não carregue software malicioso nem tente aceder à conta, aos dados ou aos ativos de outra pessoa sem autorização.", "É responsável pela exatidão das informações que fornece e pela confidencialidade das suas credenciais. Informe prontamente a KRAM se suspeitar que a sua conta foi comprometida."] },
        { heading: "3. Pedidos e contas de clientes", paragraphs: ["Enviar um pedido é apenas um primeiro contacto. Não cria automaticamente uma conta de cliente, contrato, relação de representação, reserva de capacidade ou obrigação da KRAM aceitar o trabalho.", "A equipa pode analisar o pedido e solicitar esclarecimentos. Qualquer serviço depende da confirmação do âmbito, disponibilidade, preço, responsabilidades e outras condições, normalmente num acordo escrito separado. O acesso ao portal do cliente pode ser concedido separadamente e limitado, suspenso ou retirado por razões de segurança ou operacionais."] },
        { heading: "4. Serviços e coordenação no terreno", paragraphs: ["Consoante o âmbito acordado, a KRAM pode prestar inspeções de ativos, coordenação de manutenção, acompanhamento de projetos ou construção, visibilidade de despesas, relatórios e acompanhamento contínuo. Os resultados, calendários, orçamentos, níveis de serviço e aprovações devem ser acordados para cada serviço.", "A KRAM coordena trabalhos e comunica informações para ajudar os clientes a tomar decisões informadas. Reparações, construção, inspeções ou trabalhos especializados podem ser executados por profissionais ou prestadores terceiros. Salvo acordo escrito em contrário, a KRAM não afirma que todos os prestadores são seus trabalhadores nem garante um resultado, prazo, custo ou condição específica do ativo.", "Os clientes continuam responsáveis pelas decisões e aprovações que lhes cabem segundo o contrato aplicável, incluindo a aprovação de trabalhos ou despesas quando necessária. A KRAM não é um serviço de emergência, salvo se tal estiver expressamente previsto num acordo escrito aplicável."] },
        { heading: "5. Estimativas, relatórios e decisões", paragraphs: ["Relatórios, fotografias, observações, estimativas e atualizações refletem as informações disponíveis na altura e o âmbito acordado. Uma inspeção não é necessariamente uma avaliação estrutural, análise de titularidade legal, avaliação financeira, análise ambiental ou certificação especializada, salvo se o âmbito escrito o incluir expressamente e for contratado o profissional qualificado adequado.", "Custos e prazos podem mudar devido às condições do local, disponibilidade, fornecimentos, clima, autorizações, alterações de âmbito ou outras circunstâncias. A KRAM comunicará alterações relevantes quando razoavelmente possível. O conteúdo geral do website não substitui aconselhamento jurídico, fiscal, técnico ou financeiro profissional."] },
        { heading: "6. Honorários e pagamentos", paragraphs: ["Honorários, calendário de pagamentos, impostos, custos de terceiros, limites de aprovação de despesas e condições de cancelamento ou reembolso são definidos na proposta ou contrato escrito aplicável. O website não estabelece preços nem obrigações de pagamento sem confirmação escrita explícita para o seu serviço. Não pague a alguém que afirme representar a KRAM sem verificar as instruções através de um canal autorizado."] },
        { heading: "7. Propriedade intelectual", paragraphs: ["Salvo indicação em contrário, os textos, marca, design e materiais originais do website pertencem à KRAM ou são utilizados com autorização. Pode consultá-los para uso pessoal ou avaliação interna do negócio. A reprodução, republicação, exploração comercial ou modificação que infrinja direitos ou represente incorretamente a KRAM exige autorização prévia. Relatórios e entregáveis específicos do cliente são regidos pelo contrato aplicável."] },
        { heading: "8. Serviços e ligações de terceiros", paragraphs: ["O website ou os nossos processos podem referir ferramentas, serviços de mensagens ou profissionais terceiros. Essas partes podem ter termos e práticas de privacidade próprios. A KRAM não controla nem é responsável por websites ou serviços independentes de terceiros."] },
        { heading: "9. Disponibilidade e exclusões", paragraphs: ["Procuramos manter o website útil e disponível, mas não garantimos acesso ininterrupto, sem erros ou permanente. O conteúdo é informativo e pode não descrever todos os serviços ou locais onde a KRAM pode operar. Na medida permitida pela lei, o website é disponibilizado sem garantias que não estejam expressamente previstas num acordo escrito. Nada nestes termos exclui direitos ou responsabilidades que não possam legalmente ser excluídos.", "Na medida permitida pela lei, a KRAM não é responsável por perdas indiretas decorrentes apenas da utilização deste website informativo, de interrupções de acesso ou da confiança no conteúdo geral. A responsabilidade relativa a serviços contratados é regida pelo acordo aplicável e pela lei imperativa."] },
        { heading: "10. Suspensão, alterações e lei aplicável", paragraphs: ["Podemos alterar, suspender ou remover funcionalidades por razões de manutenção, segurança, legais ou operacionais. Podemos atualizar estes termos publicando uma nova versão com uma data revista.", "A lei aplicável e o processo de resolução de litígios de cada serviço devem constar do respetivo acordo escrito. Estes termos do website não designam uma única lei aplicável a todos os países onde a KRAM ou os seus clientes possam operar."] },
        { heading: "11. Contacto", paragraphs: ["Para dúvidas sobre estes termos, utilize os links Contactar ou Enviar pedido no website da KRAM. Os contactos confirmados serão publicados quando estiverem configurados."] }
      ]
    },
    "cookie-policy": {
      title: "Política de Cookies",
      intro: "Como os cookies e tecnologias semelhantes podem ser utilizados no website da KRAM e nas ferramentas destinadas aos clientes.",
      updated,
      sections: [
        { heading: "1. O que são cookies", paragraphs: ["Os cookies são pequenos ficheiros de texto guardados pelo navegador. Tecnologias semelhantes, como armazenamento local ou identificadores de sessão, podem ajudar o website a manter uma sessão, proteger o acesso ou compreender o seu funcionamento técnico. Esta política descreve essas tecnologias de forma geral; a utilização exata pode mudar à medida que o website evolui."] },
        { heading: "2. Funcionamento essencial", paragraphs: ["As ferramentas de cliente da KRAM podem depender de cookies essenciais ou armazenamento semelhante para autenticação, manutenção de uma sessão segura, proteção de formulários e memorização de preferências técnicas. Se iniciar sessão no portal do cliente, algum armazenamento poderá ser necessário para o portal funcionar e proteger a conta. Bloquear todo o armazenamento pode impedir certas funcionalidades."] },
        { heading: "3. Análise e publicidade", paragraphs: ["Esta política não afirma que a KRAM utilize atualmente cookies publicitários ou cookies de análise de terceiros. Se forem introduzidas tecnologias não essenciais de análise, publicidade ou personalização, esta política deverá ser atualizada para identificar as finalidades e os fornecedores, e os mecanismos de consentimento ou recusa exigidos pela lei aplicável deverão ser implementados antes da sua utilização."] },
        { heading: "4. Serviços de terceiros", paragraphs: ["O website e as ferramentas de cliente podem depender de infraestrutura de terceiros, como alojamento ou autenticação. Esses serviços podem utilizar tecnologias necessárias ao seu funcionamento. Os fornecedores e tecnologias exatos devem ser confirmados na configuração publicada e na documentação atual dos prestadores."] },
        { heading: "5. Gerir cookies", paragraphs: ["A maioria dos navegadores permite consultar, bloquear ou eliminar cookies nas definições. As opções variam por navegador e dispositivo. Eliminar cookies essenciais de sessão pode terminar a sessão ou afetar funcionalidades. Os controlos do navegador não removem necessariamente todas as formas de armazenamento local."] },
        { heading: "6. Alterações e contacto", paragraphs: ["Podemos atualizar esta política quando o website ou as suas tecnologias mudarem. A data indica a versão atualmente apresentada. Para dúvidas, utilize os links Contactar ou Enviar pedido no website da KRAM."] }
      ]
    },
    faqs: {
      title: "Perguntas Frequentes",
      intro: "Um guia prático sobre como a KRAM ajuda os proprietários a acompanhar ativos à distância.",
      updated,
      sections: [
        { heading: "O que é a KRAM?", paragraphs: ["A KRAM — Kore Remote Asset Management — ajuda os proprietários a acompanhar melhor imóveis e ativos relacionados através de inspeções, coordenação de manutenção, acompanhamento de projetos, visibilidade de despesas e relatórios contínuos."] },
        { heading: "A quem se destina a KRAM?", paragraphs: ["A KRAM destina-se a proprietários e clientes que precisam de informação fiável e coordenação prática para ativos que nem sempre conseguem acompanhar presencialmente, incluindo pessoas que vivem no estrangeiro ou gerem ativos em diferentes locais."] },
        { heading: "Onde opera a KRAM?", paragraphs: ["A nossa presença atual inclui Luanda, Angola; Kinshasa, República Democrática do Congo; e Cape Town, África do Sul. A KRAM pretende crescer internacionalmente; a presença de uma cidade nesta lista não significa que todos os serviços estejam disponíveis em todas as áreas. Envie um pedido para confirmar a cobertura do seu ativo."] },
        { heading: "Que serviços posso solicitar?", paragraphs: ["Consoante o local e o âmbito, pode solicitar inspeção de ativos, coordenação de manutenção, acompanhamento de projetos ou construção, visibilidade de custos e despesas e acompanhamento contínuo do ativo. Os resultados específicos são acordados antes do início do trabalho."] },
        { heading: "Como começo?", paragraphs: ["Envie um pedido com os seus contactos, local de residência, localização e tipo do ativo e o apoio pretendido. Pode incluir até 20 ativos num único pedido inicial. A nossa equipa analisa as informações e contacta-o para discutir os próximos passos possíveis."] },
        { heading: "Enviar um pedido cria uma conta de cliente?", paragraphs: ["Não. O pedido serve apenas para iniciar uma conversa. Não cria uma conta de cliente nem o obriga a comprar serviços. A equipa analisa primeiro o pedido; a integração do cliente e qualquer contrato de serviço são processos separados."] },
        { heading: "O que acontece depois de enviar o pedido?", paragraphs: ["A equipa KRAM analisa os dados e poderá contactá-lo através do método preferido para esclarecer necessidades, confirmar disponibilidade e discutir âmbito, calendário e preço. O envio do pedido não garante que a KRAM aceite o serviço."] },
        { heading: "A KRAM pode acompanhar vários imóveis?", paragraphs: ["Pode descrever até 20 ativos num pedido inicial. Se tiver um portefólio maior ou complexo, indique-o no campo de detalhes para que a equipa possa discutir um processo de integração adequado."] },
        { heading: "Como recebo atualizações?", paragraphs: ["A abordagem centra-se em comunicação clara e atualizações apoiadas por evidências, que podem incluir constatações de inspeção, fotografias, relatórios, progresso de projetos, registos de trabalho e informações sobre despesas, conforme acordado. A frequência e os resultados dependem do âmbito escrito."] },
        { heading: "Quem executa o trabalho no meu imóvel?", paragraphs: ["A KRAM coordena e acompanha as atividades acordadas. Dependendo da tarefa, o trabalho no terreno pode ser realizado por técnicos independentes ou prestadores especializados. As responsabilidades, aprovações, verificações de qualidade e eventuais garantias devem ser confirmadas na proposta ou contrato aplicável."] },
        { heading: "Posso aprovar despesas e trabalhos?", paragraphs: ["As etapas de aprovação e os limites de despesa devem ser acordados para o seu serviço. Quando o processo exige a sua aprovação, a equipa deverá solicitá-la antes de avançar com o custo ou trabalho em causa, salvo acordo escrito diferente."] },
        { heading: "A KRAM presta serviços de emergência?", paragraphs: ["Não presuma que a KRAM presta resposta de emergência 24 horas por dia, 7 dias por semana. A disponibilidade, os contactos de escalonamento e os procedimentos urgentes devem ser confirmados expressamente no contrato de serviço. Em perigo imediato, contacte os serviços de emergência locais competentes."] },
        { heading: "Como são definidos os honorários?", paragraphs: ["Os honorários dependem do ativo, localização, serviços solicitados, âmbito, frequência, deslocações e custos de terceiros. A KRAM discutirá a proposta e as condições de pagamento antes de confirmar o serviço. O simples envio de um pedido não gera qualquer cobrança."] },
        { heading: "Como são tratadas as minhas informações?", paragraphs: ["A KRAM utiliza informações de pedidos e clientes para responder, coordenar serviços acordados, fornecer atualizações, gerir acessos e manter registos adequados. Consulte a Política de Privacidade para mais detalhes sobre dados, partilha, conservação e opções disponíveis."] },
        { heading: "Como posso contactar a KRAM?", paragraphs: ["Utilize os links Contactar ou Enviar pedido no website. Os meios de contacto disponíveis podem variar conforme a localização e serão apresentados quando confirmados."] }
      ]
    }
  }
};

export const legalNavigation: Record<Locale, { home: string; about: string; services: string; enquiry: string; portal: string; privacy: string; terms: string; cookies: string; faqs: string; contact: string; language: string }> = {
  en: { home: "Home", about: "About", services: "Services", enquiry: "Submit an Enquiry", portal: "Client Portal", privacy: "Privacy Policy", terms: "Terms of Service", cookies: "Cookie Policy", faqs: "FAQs", contact: "Contact Us", language: "Language" },
  fr: { home: "Accueil", about: "À propos", services: "Services", enquiry: "Envoyer une demande", portal: "Portail client", privacy: "Confidentialité", terms: "Conditions d'utilisation", cookies: "Politique relative aux cookies", faqs: "Questions fréquentes", contact: "Contact", language: "Langue" },
  pt: { home: "Início", about: "Sobre", services: "Serviços", enquiry: "Enviar pedido", portal: "Portal do cliente", privacy: "Privacidade", terms: "Termos de Serviço", cookies: "Política de Cookies", faqs: "Perguntas frequentes", contact: "Contactar", language: "Idioma" }
};
