import type { Locale } from "@/lib/i18n";

export const moduleCopy = {
  fr: {
    workOrders: {
      eyebrow: "Opérations", title: "Ordres de travail",
      description: "Pilotez les demandes, interventions et travaux à travers le réseau KRAM.",
      primaryAction: "Nouvel ordre de travail",
      metrics: [
        { label: "Ouverts", value: "0", hint: "Demandes actives" },
        { label: "À assigner", value: "0", hint: "En attente d’affectation" },
        { label: "En cours", value: "0", hint: "Interventions actives" },
      ],
      queueTitle: "File opérationnelle", queueDescription: "Les ordres de travail actifs apparaîtront ici.",
      emptyTitle: "Aucun ordre de travail", emptyDescription: "La file est prête. Les demandes créées pour les actifs KRAM seront suivies ici de l’approbation à la clôture.",
      workflowTitle: "Cycle de travail",
      workflow: ["Brouillon", "Approbation", "Affecté", "En cours", "Preuves", "Vérifié", "Clôturé"],
    },
    inspections: {
      eyebrow: "Opérations", title: "Inspections",
      description: "Structurez les visites terrain, constats techniques, médias et recommandations.",
      primaryAction: "Nouvelle inspection",
      metrics: [
        { label: "Planifiées", value: "0", hint: "Inspections à venir" },
        { label: "En retard", value: "0", hint: "À reprogrammer" },
        { label: "Rapports", value: "0", hint: "Rapports produits" },
      ],
      queueTitle: "Planning des inspections", queueDescription: "Les inspections à venir et récentes seront regroupées ici.",
      emptyTitle: "Aucune inspection", emptyDescription: "Créez une inspection depuis un actif pour enregistrer une checklist, des médias, des observations et des recommandations.",
      workflowTitle: "Parcours d’inspection",
      workflow: ["Planifiée", "Sur site", "Constats", "Médias", "Rapport", "Recommandations"],
    },
    projects: {
      eyebrow: "Opérations", title: "Projets",
      description: "Suivez les constructions et rénovations avec une vue claire de l’avancement et des écarts.",
      primaryAction: "Nouveau projet",
      metrics: [
        { label: "Actifs", value: "0", hint: "Projets en portefeuille" },
        { label: "En cours", value: "0", hint: "Projets actifs" },
        { label: "À risque", value: "0", hint: "Nécessitent attention" },
      ],
      queueTitle: "Portefeuille projets", queueDescription: "Les projets et leurs dernières mises à jour apparaîtront ici.",
      emptyTitle: "Aucun projet", emptyDescription: "Les projets KRAM seront structurés par actif, jalons, progression, dépenses, problèmes et preuves terrain.",
      workflowTitle: "Cycle projet",
      workflow: ["Planification", "Mobilisation", "Travaux", "Contrôle", "Clôture"],
    },
    maintenance: {
      eyebrow: "Opérations", title: "Maintenance",
      description: "Coordonnez les interventions préventives, correctives et urgentes sur les actifs.",
      primaryAction: "Planifier une intervention",
      metrics: [
        { label: "Planifiée", value: "0", hint: "Maintenance préventive" },
        { label: "Urgente", value: "0", hint: "Incidents signalés" },
        { label: "Terminée", value: "0", hint: "Interventions clôturées" },
      ],
      queueTitle: "Interventions", queueDescription: "La maintenance liée aux actifs et ordres de travail sera centralisée ici.",
      emptyTitle: "Aucune intervention", emptyDescription: "La file de maintenance est prête pour les travaux électriques, plomberie, climatisation, nettoyage, jardinage et autres interventions.",
      workflowTitle: "Cycle maintenance",
      workflow: ["Signalée", "Évaluation", "Approbation", "Intervention", "Vérification"],
    },
    providers: {
      eyebrow: "Réseau", title: "Prestataires",
      description: "Gérez le réseau terrain de KRAM, ses spécialités, sa couverture et son historique.",
      primaryAction: "Ajouter un prestataire",
      metrics: [
        { label: "Prestataires", value: "0", hint: "Réseau enregistré" },
        { label: "Vérifiés", value: "0", hint: "Prestataires validés" },
        { label: "Actifs", value: "0", hint: "Disponibles pour intervention" },
      ],
      queueTitle: "Réseau de prestataires", queueDescription: "Les techniciens et entreprises par spécialité et zone apparaîtront ici.",
      emptyTitle: "Aucun prestataire", emptyDescription: "Enregistrez les contacts terrain, spécialités, zones couvertes et vérifications pour structurer le réseau de Kinshasa puis des autres marchés.",
      workflowTitle: "Cycle prestataire",
      workflow: ["Référencé", "Vérifié", "Affecté", "Intervention", "Historique"],
    },
    expenses: {
      eyebrow: "Finance", title: "Dépenses",
      description: "Gardez le contrôle opérationnel des coûts liés aux actifs, interventions et projets.",
      primaryAction: "Enregistrer une dépense",
      metrics: [
        { label: "En attente", value: "0", hint: "À vérifier" },
        { label: "Approuvées", value: "0", hint: "Prêtes à payer" },
        { label: "Vérifiées", value: "0", hint: "Dépenses clôturées" },
      ],
      queueTitle: "Registre des dépenses", queueDescription: "Les dépenses opérationnelles et leurs preuves seront suivies ici.",
      emptyTitle: "Aucune dépense", emptyDescription: "Chaque coût sera relié à un actif ou un ordre de travail, avec bénéficiaire, preuve et état de vérification.",
      workflowTitle: "Cycle financier",
      workflow: ["Demandée", "Approuvée", "Payée", "Preuve", "Vérifiée"],
    },
    approvals: {
      eyebrow: "Finance", title: "Approbations",
      description: "Centralisez les décisions qui nécessitent l’autorisation de KRAM ou du client.",
      primaryAction: "Voir les demandes",
      metrics: [
        { label: "En attente", value: "0", hint: "Décisions à prendre" },
        { label: "Client", value: "0", hint: "Approbations externes" },
        { label: "KRAM", value: "0", hint: "Contrôles internes" },
      ],
      queueTitle: "File d’approbation", queueDescription: "Les demandes en attente apparaîtront selon leur priorité et leur contexte.",
      emptyTitle: "Aucune approbation", emptyDescription: "Les réparations, dépenses ou travaux nécessitant une décision seront regroupés dans une seule file de contrôle.",
      workflowTitle: "Cycle d’approbation",
      workflow: ["Demandée", "En revue", "Approuvée", "Refusée", "Exécutée"],
    },
    reports: {
      eyebrow: "Documents", title: "Rapports",
      description: "Conservez les rapports d’inspection, de projet et les livrables transmis aux clients.",
      primaryAction: "Créer un rapport",
      metrics: [
        { label: "Rapports", value: "0", hint: "Documents publiés" },
        { label: "Brouillons", value: "0", hint: "En préparation" },
        { label: "Transmis", value: "0", hint: "Partagés aux clients" },
      ],
      queueTitle: "Bibliothèque de rapports", queueDescription: "Les rapports produits par KRAM seront accessibles depuis leur actif.",
      emptyTitle: "Aucun rapport", emptyDescription: "Les rapports pourront regrouper résumé exécutif, observations, photos, vidéos, coûts, recommandations et chronologie.",
      workflowTitle: "Cycle documentaire",
      workflow: ["Brouillon", "Révision", "Publié", "Transmis", "Archivé"],
    },
    activity: {
      eyebrow: "Système", title: "Activité",
      description: "Suivez les événements importants du système et répondez à la question : qui a fait quoi, et quand ?",
      metrics: [
        { label: "Événements", value: "0", hint: "Journal d’activité" },
        { label: "Aujourd’hui", value: "0", hint: "Nouveaux événements" },
        { label: "Utilisateurs", value: "0", hint: "Acteurs récents" },
      ],
      queueTitle: "Journal d’activité", queueDescription: "Les événements d’audit apparaîtront dans l’ordre chronologique.",
      emptyTitle: "Aucune activité enregistrée", emptyDescription: "Les actions sur les actifs, ordres de travail, approbations, dépenses et comptes utilisateurs seront journalisées ici.",
      workflowTitle: "Événements suivis",
      workflow: ["Créé", "Modifié", "Approuvé", "Documenté", "Vérifié", "Clôturé"],
    },
  },
  en: {
    workOrders: {
      eyebrow: "Operations", title: "Work Orders",
      description: "Control requests, interventions and field work across the KRAM network.",
      primaryAction: "New work order",
      metrics: [
        { label: "Open", value: "0", hint: "Active requests" },
        { label: "Unassigned", value: "0", hint: "Awaiting assignment" },
        { label: "In progress", value: "0", hint: "Active interventions" },
      ],
      queueTitle: "Operations queue", queueDescription: "Active work orders will appear here.",
      emptyTitle: "No work orders", emptyDescription: "The queue is ready. Requests created for KRAM assets will be tracked here from approval through closure.",
      workflowTitle: "Work cycle", workflow: ["Draft", "Approval", "Assigned", "In progress", "Evidence", "Verified", "Closed"],
    },
    inspections: {
      eyebrow: "Operations", title: "Inspections",
      description: "Structure site visits, technical findings, media and recommendations.",
      primaryAction: "New inspection",
      metrics: [
        { label: "Scheduled", value: "0", hint: "Upcoming inspections" },
        { label: "Overdue", value: "0", hint: "Need rescheduling" },
        { label: "Reports", value: "0", hint: "Reports produced" },
      ],
      queueTitle: "Inspection schedule", queueDescription: "Upcoming and recent inspections will be grouped here.",
      emptyTitle: "No inspections", emptyDescription: "Create an inspection from an asset to record a checklist, media, observations and recommendations.",
      workflowTitle: "Inspection flow", workflow: ["Scheduled", "On site", "Findings", "Media", "Report", "Recommendations"],
    },
    projects: {
      eyebrow: "Operations", title: "Projects",
      description: "Track construction and renovation work with a clear view of progress and exceptions.",
      primaryAction: "New project",
      metrics: [
        { label: "Portfolio", value: "0", hint: "Projects tracked" },
        { label: "Active", value: "0", hint: "Projects in progress" },
        { label: "At risk", value: "0", hint: "Need attention" },
      ],
      queueTitle: "Project portfolio", queueDescription: "Projects and their latest updates will appear here.",
      emptyTitle: "No projects", emptyDescription: "KRAM projects will be structured by asset, milestones, progress, costs, issues and field evidence.",
      workflowTitle: "Project cycle", workflow: ["Planning", "Mobilization", "Works", "Control", "Closeout"],
    },
    maintenance: {
      eyebrow: "Operations", title: "Maintenance",
      description: "Coordinate preventive, corrective and urgent interventions across assets.",
      primaryAction: "Schedule intervention",
      metrics: [
        { label: "Scheduled", value: "0", hint: "Preventive maintenance" },
        { label: "Urgent", value: "0", hint: "Reported incidents" },
        { label: "Completed", value: "0", hint: "Closed interventions" },
      ],
      queueTitle: "Interventions", queueDescription: "Maintenance tied to assets and work orders will be centralized here.",
      emptyTitle: "No interventions", emptyDescription: "The maintenance queue is ready for electrical, plumbing, HVAC, cleaning, landscaping and other field work.",
      workflowTitle: "Maintenance cycle", workflow: ["Reported", "Assessment", "Approval", "Intervention", "Verification"],
    },
    providers: {
      eyebrow: "Network", title: "Service Providers",
      description: "Manage KRAM's field network, specialties, coverage and operational history.",
      primaryAction: "Add provider",
      metrics: [
        { label: "Providers", value: "0", hint: "Registered network" },
        { label: "Verified", value: "0", hint: "Validated providers" },
        { label: "Active", value: "0", hint: "Available for work" },
      ],
      queueTitle: "Provider network", queueDescription: "Technicians and companies by specialty and area will appear here.",
      emptyTitle: "No service providers", emptyDescription: "Register field contacts, specialties, coverage areas and verification status to structure the network in Kinshasa and future markets.",
      workflowTitle: "Provider cycle", workflow: ["Registered", "Verified", "Assigned", "Intervention", "History"],
    },
    expenses: {
      eyebrow: "Finance", title: "Expenses",
      description: "Maintain operational control over costs tied to assets, interventions and projects.",
      primaryAction: "Record expense",
      metrics: [
        { label: "Pending", value: "0", hint: "Need verification" },
        { label: "Approved", value: "0", hint: "Ready for payment" },
        { label: "Verified", value: "0", hint: "Closed expenses" },
      ],
      queueTitle: "Expense ledger", queueDescription: "Operational expenses and their evidence will be tracked here.",
      emptyTitle: "No expenses", emptyDescription: "Each cost will link to an asset or work order, with payee, evidence and verification status.",
      workflowTitle: "Finance cycle", workflow: ["Requested", "Approved", "Paid", "Evidence", "Verified"],
    },
    approvals: {
      eyebrow: "Finance", title: "Approvals",
      description: "Centralize decisions requiring KRAM or client authorization.",
      primaryAction: "Review requests",
      metrics: [
        { label: "Pending", value: "0", hint: "Decisions required" },
        { label: "Client", value: "0", hint: "External approvals" },
        { label: "KRAM", value: "0", hint: "Internal controls" },
      ],
      queueTitle: "Approval queue", queueDescription: "Pending decisions will be ordered by priority and context.",
      emptyTitle: "No approvals", emptyDescription: "Repairs, expenses or work requiring a decision will be grouped into one control queue.",
      workflowTitle: "Approval cycle", workflow: ["Requested", "Review", "Approved", "Rejected", "Executed"],
    },
    reports: {
      eyebrow: "Documents", title: "Reports",
      description: "Keep inspection reports, project updates and client deliverables in one place.",
      primaryAction: "Create report",
      metrics: [
        { label: "Reports", value: "0", hint: "Published documents" },
        { label: "Drafts", value: "0", hint: "In preparation" },
        { label: "Sent", value: "0", hint: "Shared with clients" },
      ],
      queueTitle: "Report library", queueDescription: "Reports produced by KRAM will be accessible from their asset context.",
      emptyTitle: "No reports", emptyDescription: "Reports can bring together executive summary, observations, photos, videos, costs, recommendations and timeline.",
      workflowTitle: "Document cycle", workflow: ["Draft", "Review", "Published", "Sent", "Archived"],
    },
    activity: {
      eyebrow: "System", title: "Activity",
      description: "Track important system events and answer: who did what, and when?",
      metrics: [
        { label: "Events", value: "0", hint: "Audit log" },
        { label: "Today", value: "0", hint: "New events" },
        { label: "Users", value: "0", hint: "Recent actors" },
      ],
      queueTitle: "Activity log", queueDescription: "Audit events will appear in chronological order.",
      emptyTitle: "No activity recorded yet", emptyDescription: "Actions across assets, work orders, approvals, expenses and user accounts will be logged here.",
      workflowTitle: "Tracked events", workflow: ["Created", "Updated", "Approved", "Documented", "Verified", "Closed"],
    },
  },
  pt: {
    workOrders: {
      eyebrow: "Operações", title: "Ordens de trabalho",
      description: "Controle pedidos, intervenções e trabalhos de campo em toda a rede KRAM.",
      primaryAction: "Nova ordem de trabalho",
      metrics: [
        { label: "Abertas", value: "0", hint: "Pedidos ativos" },
        { label: "Por atribuir", value: "0", hint: "Aguardando atribuição" },
        { label: "Em curso", value: "0", hint: "Intervenções ativas" },
      ],
      queueTitle: "Fila operacional", queueDescription: "As ordens de trabalho ativas aparecerão aqui.",
      emptyTitle: "Ainda não há ordens de trabalho", emptyDescription: "A fila está pronta. Os pedidos criados para os ativos KRAM serão acompanhados da aprovação ao encerramento.",
      workflowTitle: "Ciclo de trabalho", workflow: ["Rascunho", "Aprovação", "Atribuída", "Em curso", "Evidências", "Verificada", "Encerrada"],
    },
    inspections: {
      eyebrow: "Operações", title: "Inspeções",
      description: "Estruture visitas de campo, constatações técnicas, meios e recomendações.",
      primaryAction: "Nova inspeção",
      metrics: [
        { label: "Agendadas", value: "0", hint: "Próximas inspeções" },
        { label: "Em atraso", value: "0", hint: "Necessitam reagendamento" },
        { label: "Relatórios", value: "0", hint: "Relatórios produzidos" },
      ],
      queueTitle: "Agenda de inspeções", queueDescription: "As inspeções próximas e recentes serão agrupadas aqui.",
      emptyTitle: "Ainda não há inspeções", emptyDescription: "Crie uma inspeção a partir de um ativo para registar checklist, meios, observações e recomendações.",
      workflowTitle: "Fluxo da inspeção", workflow: ["Agendada", "No local", "Constatações", "Meios", "Relatório", "Recomendações"],
    },
    projects: {
      eyebrow: "Operações", title: "Projetos",
      description: "Acompanhe obras e remodelações com uma visão clara do progresso e das exceções.",
      primaryAction: "Novo projeto",
      metrics: [
        { label: "Portefólio", value: "0", hint: "Projetos acompanhados" },
        { label: "Ativos", value: "0", hint: "Projetos em curso" },
        { label: "Em risco", value: "0", hint: "Requerem atenção" },
      ],
      queueTitle: "Portefólio de projetos", queueDescription: "Os projetos e as suas atualizações mais recentes aparecerão aqui.",
      emptyTitle: "Ainda não há projetos", emptyDescription: "Os projetos KRAM serão estruturados por ativo, marcos, progresso, custos, problemas e evidências de campo.",
      workflowTitle: "Ciclo do projeto", workflow: ["Planeamento", "Mobilização", "Obras", "Controlo", "Encerramento"],
    },
    maintenance: {
      eyebrow: "Operações", title: "Manutenção",
      description: "Coordene intervenções preventivas, corretivas e urgentes nos ativos.",
      primaryAction: "Agendar intervenção",
      metrics: [
        { label: "Agendada", value: "0", hint: "Manutenção preventiva" },
        { label: "Urgente", value: "0", hint: "Incidentes comunicados" },
        { label: "Concluída", value: "0", hint: "Intervenções encerradas" },
      ],
      queueTitle: "Intervenções", queueDescription: "A manutenção ligada aos ativos e ordens de trabalho será centralizada aqui.",
      emptyTitle: "Ainda não há intervenções", emptyDescription: "A fila de manutenção está pronta para trabalhos elétricos, canalização, climatização, limpeza, jardinagem e outros serviços.",
      workflowTitle: "Ciclo de manutenção", workflow: ["Comunicada", "Avaliação", "Aprovação", "Intervenção", "Verificação"],
    },
    providers: {
      eyebrow: "Rede", title: "Prestadores",
      description: "Gira a rede de campo da KRAM, especialidades, cobertura e histórico operacional.",
      primaryAction: "Adicionar prestador",
      metrics: [
        { label: "Prestadores", value: "0", hint: "Rede registada" },
        { label: "Verificados", value: "0", hint: "Prestadores validados" },
        { label: "Ativos", value: "0", hint: "Disponíveis para trabalhos" },
      ],
      queueTitle: "Rede de prestadores", queueDescription: "Técnicos e empresas por especialidade e zona aparecerão aqui.",
      emptyTitle: "Ainda não há prestadores", emptyDescription: "Registe contactos de campo, especialidades, zonas de cobertura e estado de verificação para estruturar a rede em Kinshasa e futuros mercados.",
      workflowTitle: "Ciclo do prestador", workflow: ["Registado", "Verificado", "Atribuído", "Intervenção", "Histórico"],
    },
    expenses: {
      eyebrow: "Finanças", title: "Despesas",
      description: "Mantenha controlo operacional dos custos ligados a ativos, intervenções e projetos.",
      primaryAction: "Registar despesa",
      metrics: [
        { label: "Pendentes", value: "0", hint: "A verificar" },
        { label: "Aprovadas", value: "0", hint: "Prontas para pagamento" },
        { label: "Verificadas", value: "0", hint: "Despesas encerradas" },
      ],
      queueTitle: "Registo de despesas", queueDescription: "As despesas operacionais e respetivas provas serão acompanhadas aqui.",
      emptyTitle: "Ainda não há despesas", emptyDescription: "Cada custo será ligado a um ativo ou ordem de trabalho, com beneficiário, prova e estado de verificação.",
      workflowTitle: "Ciclo financeiro", workflow: ["Solicitada", "Aprovada", "Paga", "Prova", "Verificada"],
    },
    approvals: {
      eyebrow: "Finanças", title: "Aprovações",
      description: "Centralize decisões que exigem autorização da KRAM ou do cliente.",
      primaryAction: "Rever pedidos",
      metrics: [
        { label: "Pendentes", value: "0", hint: "Decisões necessárias" },
        { label: "Cliente", value: "0", hint: "Aprovações externas" },
        { label: "KRAM", value: "0", hint: "Controlos internos" },
      ],
      queueTitle: "Fila de aprovação", queueDescription: "As decisões pendentes serão organizadas por prioridade e contexto.",
      emptyTitle: "Ainda não há aprovações", emptyDescription: "Reparações, despesas ou trabalhos que exigem decisão serão agrupados numa única fila de controlo.",
      workflowTitle: "Ciclo de aprovação", workflow: ["Solicitada", "Em revisão", "Aprovada", "Recusada", "Executada"],
    },
    reports: {
      eyebrow: "Documentos", title: "Relatórios",
      description: "Conserve relatórios de inspeção, atualizações de projetos e entregáveis para clientes num só lugar.",
      primaryAction: "Criar relatório",
      metrics: [
        { label: "Relatórios", value: "0", hint: "Documentos publicados" },
        { label: "Rascunhos", value: "0", hint: "Em preparação" },
        { label: "Enviados", value: "0", hint: "Partilhados com clientes" },
      ],
      queueTitle: "Biblioteca de relatórios", queueDescription: "Os relatórios produzidos pela KRAM ficarão acessíveis a partir do seu ativo.",
      emptyTitle: "Ainda não há relatórios", emptyDescription: "Os relatórios poderão reunir resumo executivo, observações, fotos, vídeos, custos, recomendações e cronologia.",
      workflowTitle: "Ciclo documental", workflow: ["Rascunho", "Revisão", "Publicado", "Enviado", "Arquivado"],
    },
    activity: {
      eyebrow: "Sistema", title: "Atividade",
      description: "Acompanhe eventos importantes do sistema e responda: quem fez o quê e quando?",
      metrics: [
        { label: "Eventos", value: "0", hint: "Registo de auditoria" },
        { label: "Hoje", value: "0", hint: "Novos eventos" },
        { label: "Utilizadores", value: "0", hint: "Autores recentes" },
      ],
      queueTitle: "Registo de atividade", queueDescription: "Os eventos de auditoria aparecerão por ordem cronológica.",
      emptyTitle: "Ainda não há atividade", emptyDescription: "As ações sobre ativos, ordens de trabalho, aprovações, despesas e contas de utilizadores serão registadas aqui.",
      workflowTitle: "Eventos acompanhados", workflow: ["Criado", "Atualizado", "Aprovado", "Documentado", "Verificado", "Encerrado"],
    },
  },
} as const;

export function getModuleCopy(locale: Locale, key: keyof (typeof moduleCopy)["en"]) {
  return moduleCopy[locale][key];
}
