import type { Locale } from "@/lib/i18n";

/**
 * Public footer details are sourced centrally. Contact and social links stay
 * unpublished until the corresponding deployment environment variables exist.
 */
export const publicFooter = {
  email: process.env.NEXT_PUBLIC_KRAM_EMAIL?.trim() || "",
  phoneNumber: process.env.NEXT_PUBLIC_KRAM_PHONE_NUMBER?.replace(/\D/g, "") || "",
  whatsappNumber: process.env.NEXT_PUBLIC_KRAM_WHATSAPP_NUMBER?.replace(/\D/g, "") || "",
  socials: {
    linkedin: process.env.NEXT_PUBLIC_KRAM_LINKEDIN_URL?.trim() || "",
    instagram: process.env.NEXT_PUBLIC_KRAM_INSTAGRAM_URL?.trim() || "",
    facebook: process.env.NEXT_PUBLIC_KRAM_FACEBOOK_URL?.trim() || "",
  },
  footprint: [
    "Luanda, Angola",
    "Kinshasa, Democratic Republic of the Congo",
    "Cape Town, South Africa",
  ],
  branch: {
    address: "Via Expressa - Nova Era, Cacuaco",
    reference: "Officina - antes da TotalEnergies Sequele",
    city: "Luanda, Angola",
  },
};

export const footerLabels: Record<Locale, Record<string, string>> = {
  en: {
    company: "Kore Remote Asset Management",
    tagline: "Asset oversight with clarity and accountability.",
    contact: "Contact",
    start: "Get started",
    explore: "Explore",
    resources: "Client resources",
    legal: "Legal",
    faqs: "FAQs", privacy: "Privacy Policy", terms: "Terms of Service", cookies: "Cookie Policy",
    enquiry: "Submit an Enquiry",
    portal: "Client Portal",
    footprint: "Current footprint",
    growing: "Growing internationally — not limited to these locations.",
    getInTouch: "Get in touch",
    email: "Email",
    phone: "Phone",
    contactUs: "Contact Us",
    whatsapp: "WhatsApp",
    socials: "Socials",
    branch: "Main Branch",
    reference: "Reference",
    rights: "All rights reserved.",
  },
  fr: {
    company: "Kore Remote Asset Management",
    tagline: "Le suivi des actifs, avec clarté et responsabilité.",
    contact: "Contact",
    start: "Parlons de votre actif",
    explore: "Explorer",
    resources: "Espace client",
    legal: "Mentions légales",
    faqs: "Questions fréquentes", privacy: "Confidentialité", terms: "Conditions d’utilisation", cookies: "Politique relative aux cookies",
    enquiry: "Envoyer une demande",
    portal: "Portail client",
    footprint: "Présence actuelle",
    growing: "Expansion internationale — ces lieux ne sont pas nos seules destinations.",
    getInTouch: "Nous contacter",
    email: "E-mail",
    phone: "Téléphone",
    contactUs: "Nous contacter",
    whatsapp: "WhatsApp",
    socials: "Réseaux sociaux",
    branch: "Agence principale",
    reference: "Repère",
    rights: "Tous droits réservés.",
  },
  pt: {
    company: "Kore Remote Asset Management",
    tagline: "Acompanhamento de ativos com clareza e responsabilidade.",
    contact: "Contacto",
    start: "Vamos conversar",
    explore: "Explorar",
    resources: "Recursos do cliente",
    legal: "Informação legal",
    faqs: "Perguntas frequentes", privacy: "Política de Privacidade", terms: "Termos de Serviço", cookies: "Política de Cookies",
    enquiry: "Enviar uma solicitação",
    portal: "Portal do cliente",
    footprint: "Presença atual",
    growing: "Em expansão internacional — não nos limitamos a estas localizações.",
    getInTouch: "Entre em contacto",
    email: "E-mail",
    phone: "Telefone",
    contactUs: "Contactar",
    whatsapp: "WhatsApp",
    socials: "Redes sociais",
    branch: "Sede principal",
    reference: "Referência",
    rights: "Todos os direitos reservados.",
  },
};
