"use client";

import { useState } from "react";
import { Check, ChevronDown, X } from "lucide-react";
import type { Locale } from "@/lib/i18n";

const categories = {
 fr:[["maintenance","Maintenance"],["materials","Matériaux"],["utilities","Services publics"],["transport","Transport"],["labour","Main-d’œuvre"],["cleaning","Nettoyage"],["security","Sécurité"],["professional_services","Services professionnels"],["insurance","Assurance"],["taxes_fees","Taxes et frais"],["office_admin","Bureau et administration"],["other","Autre"]],
 en:[["maintenance","Maintenance"],["materials","Materials"],["utilities","Utilities"],["transport","Transport"],["labour","Labour"],["cleaning","Cleaning"],["security","Security"],["professional_services","Professional services"],["insurance","Insurance"],["taxes_fees","Taxes & fees"],["office_admin","Office & administration"],["other","Other"]],
 pt:[["maintenance","Manutenção"],["materials","Materiais"],["utilities","Serviços públicos"],["transport","Transporte"],["labour","Mão de obra"],["cleaning","Limpeza"],["security","Segurança"],["professional_services","Serviços profissionais"],["insurance","Seguro"],["taxes_fees","Impostos e taxas"],["office_admin","Escritório e administração"],["other","Outro"]]
} as const;
const ui={fr:{label:"Catégorie",choose:"Choisir une catégorie",hint:"Choisissez une catégorie standard pour des rapports cohérents.",cancel:"Annuler"},en:{label:"Category",choose:"Choose an expense category",hint:"Choose a standard category for consistent reporting.",cancel:"Cancel"},pt:{label:"Categoria",choose:"Escolher categoria de despesa",hint:"Escolha uma categoria padrão para relatórios consistentes.",cancel:"Cancelar"}} as const;
export function ExpenseCategoryPicker({name="category",defaultValue="other",locale}:{name?:string;defaultValue?:string;locale:Locale}){
 const [selected,setSelected]=useState(defaultValue);const[open,setOpen]=useState(false);const t=ui[locale];const options=categories[locale] as readonly (readonly [string,string])[];const selectedLabel=options.find(x=>x[0]===selected)?.[1]??selected;
 return <div><input type="hidden" name={name} value={selected}/><span className="mb-1.5 block text-xs font-semibold">{t.label}</span><button type="button" onClick={()=>setOpen(true)} className="flex w-full items-center justify-between rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-left text-sm hover:border-zinc-400"><span>{selectedLabel}</span><ChevronDown size={16} className="text-zinc-400"/></button>
 {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><section role="dialog" aria-modal="true" aria-label={t.choose} className="w-full max-w-lg overflow-hidden rounded-2xl border border-[var(--kram-border)] bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-zinc-100 px-5 py-4"><div><h2 className="text-base font-bold text-zinc-950">{t.choose}</h2><p className="mt-1 text-xs text-zinc-500">{t.hint}</p></div><button type="button" onClick={()=>setOpen(false)} aria-label={t.cancel} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-100"><X size={17}/></button></header><div className="grid gap-2 p-4 sm:grid-cols-2">{options.map(([value,label])=><button key={value} type="button" onClick={()=>{setSelected(value);setOpen(false);}} className={`flex items-center justify-between rounded-xl border px-3.5 py-3 text-left text-sm font-semibold transition ${selected===value?"border-[var(--kram-orange)] bg-orange-50 text-zinc-950":"border-zinc-200 hover:bg-zinc-50"}`}><span>{label}</span>{selected===value&&<Check size={15} className="text-[var(--kram-orange)]"/>}</button>)}</div><footer className="flex justify-end border-t border-zinc-100 px-5 py-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-zinc-200 px-4 py-2 text-xs font-semibold">{t.cancel}</button></footer></section></div>}
 </div>;
}
