"use client";
import {useActionState,useEffect} from "react";
import {useRouter} from "next/navigation";
import {Loader2,Save} from "lucide-react";
import {updateClientRecord} from "../actions";
import type {Locale} from "@/lib/i18n";
type Client={id:string;full_name:string;email:string|null;primary_phone:string|null;alternative_phone:string|null;residency_country:string|null;residency_city:string|null;residency_address:string|null;preferred_language:string;preferred_contact_method:string;notes:string|null};
const labels={fr:{name:"Nom complet",email:"E-mail",phone:"Téléphone principal",altPhone:"Téléphone secondaire",country:"Pays de résidence",city:"Ville",address:"Adresse",language:"Langue préférée",contact:"Mode de contact préféré",notes:"Notes opérationnelles",save:"Enregistrer les modifications",saving:"Enregistrement...",cancel:"Annuler"},en:{name:"Full name",email:"Email",phone:"Primary phone",altPhone:"Alternative phone",country:"Country of residence",city:"City",address:"Address",language:"Preferred language",contact:"Preferred contact method",notes:"Operational notes",save:"Save changes",saving:"Saving...",cancel:"Cancel"},pt:{name:"Nome completo",email:"E-mail",phone:"Telefone principal",altPhone:"Telefone alternativo",country:"País de residência",city:"Cidade",address:"Morada",language:"Idioma preferido",contact:"Método de contacto preferido",notes:"Notas operacionais",save:"Guardar alterações",saving:"A guardar...",cancel:"Cancelar"}} as const;
const field="w-full rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-[var(--kram-orange)]";
function Input({label,name,value,type="text"}:{label:string;name:string;value:string;type?:string}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-zinc-700">{label}</span><input className={field} name={name} type={type} defaultValue={value}/></label>}
export function ClientEditForm({locale,client}:{locale:Locale;client:Client}){
 const t=labels[locale];const[state,action,pending]=useActionState(updateClientRecord,{success:false,message:""});const router=useRouter();
 useEffect(()=>{if(state.success)router.push("/"+locale+"/ops/clients/"+client.id);},[state,locale,client.id,router]);
 return <form action={action} className="space-y-6 rounded-2xl border border-[var(--kram-border)] bg-white p-6"><input type="hidden" name="clientId" value={client.id}/><div className="grid gap-5 md:grid-cols-2"><Input label={t.name} name="fullName" value={client.full_name}/><Input label={t.email} name="email" type="email" value={client.email??""}/><Input label={t.phone} name="primaryPhone" value={client.primary_phone??""}/><Input label={t.altPhone} name="alternativePhone" value={client.alternative_phone??""}/><Input label={t.country} name="residencyCountry" value={client.residency_country??""}/><Input label={t.city} name="residencyCity" value={client.residency_city??""}/><div className="md:col-span-2"><Input label={t.address} name="residencyAddress" value={client.residency_address??""}/></div><label><span className="mb-1.5 block text-xs font-semibold text-zinc-700">{t.language}</span><select name="preferredLanguage" defaultValue={client.preferred_language||"fr"} className={field}><option value="fr">Français</option><option value="en">English</option><option value="pt">Português</option></select></label><label><span className="mb-1.5 block text-xs font-semibold text-zinc-700">{t.contact}</span><select name="preferredContactMethod" defaultValue={client.preferred_contact_method||"whatsapp"} className={field}><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="phone">{locale==="fr"?"Téléphone":locale==="pt"?"Telefone":"Phone"}</option></select></label></div><label className="block"><span className="mb-1.5 block text-xs font-semibold text-zinc-700">{t.notes}</span><textarea name="notes" rows={4} defaultValue={client.notes??""} className={field}/></label>{state.message&&<p role="status" className={`rounded-xl px-3.5 py-3 text-xs font-medium ${state.success?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{state.message}</p>}<div className="flex flex-wrap justify-end gap-3 border-t border-zinc-100 pt-5"><button type="button" onClick={()=>router.push("/"+locale+"/ops/clients/"+client.id)} className="rounded-xl border border-zinc-200 px-4 py-3 text-sm font-semibold text-zinc-700">{t.cancel}</button><button disabled={pending} className="inline-flex items-center gap-2 rounded-xl bg-[var(--kram-charcoal)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} {pending?t.saving:t.save}</button></div></form>;
}
