import Link from "next/link";
import { notFound } from "next/navigation";
import { UsersRound, Plus, ArrowRight } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { copy, isLocale, type Locale } from "@/lib/i18n";
import { opsLabels } from "@/lib/ops-labels";
export default async function ProvidersPage({params}:{params:Promise<{locale:string}>}) {
 const {locale}=await params; if(!isLocale(locale)) notFound(); const t=copy[locale as Locale]; const labels = opsLabels(locale as Locale); const ui=locale==="fr"?{title:"Prestataires de services",desc:"Réseau KRAM de techniciens et professionnels de terrain.",add:"Ajouter un prestataire",active:"Actifs",pending:"En attente",verified:"Inactifs",network:"Réseau terrain",coverage:"Couverture non renseignée",noPhone:"Aucun téléphone",empty:"Aucun prestataire pour le moment",emptyDesc:"Commencez à constituer le réseau terrain de KRAM."}:{...locale==="pt"?{title:"Prestadores de serviços",desc:"Rede KRAM de técnicos e profissionais no terreno.",add:"Adicionar prestador",active:"Ativos",pending:"Pendentes",verified:"Inativos",network:"Rede de terreno",coverage:"Cobertura não registada",noPhone:"Sem telefone",empty:"Ainda não há prestadores",emptyDesc:"Comece a construir a rede de terreno do KRAM."}:{title:"Service providers",desc:"KRAM field network of technicians and service professionals.",add:"Add provider",active:"Active",pending:"Pending",verified:"Inactive",network:"Field network",coverage:"Coverage not recorded",noPhone:"No phone",empty:"No service providers yet",emptyDesc:"Start building KRAM’s field network."}}; const s=await createClient();
 const {data:rows}=await s.from("service_providers").select("id,name,phone,status,coverage").order("name"); const all=rows??[];
 const active=all.filter(x=>x.status==="active").length; const pending=all.filter(x=>x.status==="prospect").length; const verified=all.filter(x=>["suspended","archived"].includes(x.status)).length;
 return <div className="space-y-7"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--kram-orange)]">{t.nav.providers}</p><div className="mt-2 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--kram-charcoal)] text-white"><UsersRound size={19}/></div><h1 className="text-3xl font-bold tracking-[-0.045em] text-zinc-950">{ui.title}</h1></div><p className="mt-3 text-sm leading-6 text-zinc-500">{ui.desc}</p></div><Link href={"/"+locale+"/ops/providers/new"} className="inline-flex items-center gap-2 rounded-xl bg-[var(--kram-orange)] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/> {ui.add}</Link></section>
 <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--kram-border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-400">{ui.pending}</p><p className="mt-3 text-3xl font-bold text-zinc-950">{pending}</p></div><div className="rounded-2xl border border-[var(--kram-border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-400">{ui.active}</p><p className="mt-3 text-3xl font-bold text-zinc-950">{active}</p></div><div className="rounded-2xl border border-[var(--kram-border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-400">{ui.verified}</p><p className="mt-3 text-3xl font-bold text-zinc-950">{verified}</p></div></section>
 <section className="overflow-hidden rounded-2xl border border-[var(--kram-border)] bg-white"><div className="border-b border-zinc-100 px-5 py-4"><h2 className="text-base font-bold">{ui.network}</h2></div>{all.length?<div className="divide-y divide-zinc-100">{all.map(p=><Link key={p.id} href={"/"+locale+"/ops/providers/"+p.id} className="flex items-center justify-between gap-5 px-5 py-4 hover:bg-zinc-50"><div><p className="text-sm font-bold text-zinc-900">{p.name}</p><p className="mt-1 text-xs text-zinc-400">{p.coverage||ui.coverage} · {p.phone||ui.noPhone}</p></div><div className="flex items-center gap-3"><span className="rounded-full border border-zinc-200 px-2.5 py-1 text-[11px] font-semibold text-zinc-600">{p.status==="prospect"?(locale==="fr"?"En attente":locale==="pt"?"Pendente":"Pending"):["suspended","archived"].includes(p.status)?(locale==="fr"?"Inactif":locale==="pt"?"Inativo":"Inactive"):(locale==="fr"?"Actif":locale==="pt"?"Ativo":"Active")}</span><ArrowRight size={16} className="text-zinc-300"/></div></Link>)}</div>:<div className="flex min-h-72 flex-col items-center justify-center text-center"><UsersRound size={22} className="text-zinc-300"/><h3 className="mt-4 text-sm font-bold">{ui.empty}</h3><p className="mt-1 text-sm text-zinc-500">{ui.emptyDesc}</p></div>}</section></div>;
}